module.exports= {
    "NEW<i></i>": "नया <i></i>",
    "NEW": "नया",
    "New Cars": "नई कारें",
    "Search New Cars": "नई कारें खोजें",
    "Latest Cars": "नवीनतम कारें",
    "Popular Cars": "लोकप्रिय कारें",
    "Upcoming Cars": "आने वाली कारें",
    "Offers and Discount": "ऑफ़र और डिस्काउंट",
    "Dealers & Service Centers <i></i>": "व्यापारियों और सेवा केंद्रों <i></i>",
    "Dealers": "सौदागर",
    "Service Centers": "सेवा केंद्र",
    "Win iPhone": "विन आईफोन",
    "Renault KWID <span class='sponsoredmenu'><p>Ad</p></span>": "रीनॉल्ट क्विड <p> <span class='sponsoredmenu'>विज्ञापन</span> </p>",
    "Renault KWID": "रेनॉल्ट केडब्ल्यूआईडी",
    "USED<i></i>": "उपयोग किया गया <i></i>",
    "Cars In Your City <i></i>": "आपके शहर में कारें <i></i>",
    "Cars In Your City": "आपके शहर में कारें",
    "Ahmedabad": "अहमदाबाद",
    "Used Cars In Ahmedabad": "अहमदाबाद में प्रयुक्त कारें",
    "Bangalore": "बैंगलोर",
    "Used Cars In Bangalore": "बैंगलोर में प्रयुक्त कारें",
    "Chennai": "चेन्नई",
    "Used Cars In Chennai": "चेन्नई में सेकेंड हैंड कार",
    "Delhi NCR": "दिल्ली एनसीआर",
    "Used Cars In Delhi NCR": "दिल्ली एनसीआर में प्रयुक्त कारें",
    "Hyderabad": "हैदराबाद",
    "Used Cars In Hyderabad": "हैदराबाद में प्रयुक्त कारें",
    "Jaipur": "जयपुर",
    "Used Cars In Jaipur": "जयपुर में प्रयुक्त कारें",
    "Kolkata": "कोलकाता",
    "Used Cars In Kolkata": "कोलकाता में प्रयुक्त कारें",
    "Mumbai": "मुंबई",
    "Used Cars In Mumbai": "मुंबई में प्रयुक्त कारें",
    "Pune": "रखना",
    "Used Cars In Pune": "पुणे में प्रयुक्त कारें",
    "More Citie": "अधिक सीटी",
    "Used Cars In More Cities": "अधिक शहरों में प्रयुक्त कारें",
    "Search Used Cars": "प्रयुक्त कारें खोजें",
    "Sell Used Cars": "प्रयुक्त कारें बेचें",
    "Used Car Valuation": "प्रयुक्त कार मूल्यांकन",
    "My Listing": "मेरी लिस्टिंग",
    "CarDekho Trustmark": "CarDekho ट्रस्टमार्क",
    "UsedCar Dealer": "प्रयुक्त कर डीलर",
    "SELL": "बेचना",
    "Sell Cars": "कारें बेचें",
    "COMPARE": "की तुलना करें",
    "Compare": "की तुलना करें",
    "Compare Cars": "कारों की तुलना करें",
    "NEWS & REVIEWS <i></i>": "समाचार और समीक्षा <i></i>",
    "News & Reviews Cars": "समाचार और समीक्षा कारें",
    "Car News": "कार समाचार",
    "Feature Stories": "फ़ीचर कहानियां",
    "User Reviews": "उपयोगकर्ता समीक्षा",
    "Road Test": "सड़क परीक्षण",
    "Car Videos": "कार वीडियो",
    "Write Review": "समीक्षा लिखें",
    "MORE <i></i>": "अधिक <i></i>",
    "Car Loan": "कार ऋण",
    "EMI Calculator": "ईएमआई कैलकुलेटर",
    "Safety Month": "सुरक्षा माह",
    "Car Insurance": "कार बीमा",
    "Car Tyres//<span class='sponsoredmenu'>Firestone<p>Ad</p></span>": "कार टायर // <span class='sponsoredmenu'>फायरस्टोन</span> <p> <span class='sponsoredmenu'>विज्ञापन</span> </p>",
    "Car Tyres" : "कार टायर",
    "Ask A Question": "प्रश्न पूछें",
    "<span class='icon-new-car menusIcon'></span>New Cars<i data-icon-arrow-left='withoutfill'></i>": "<span class='icon-new-car menusIcon'></span> नई कारें <i data-icon-arrow-left='withoutfill'></i>",
    "360 Degree View": "360 डिग्री देखें",
    "Offers & Discounts": "ऑफ़र और छूट",
    "Renault KWID <span class='sponsoredmenu float-right'><p>Ad</p></span>": "रीनॉल्ट क्विड <p> <span class='sponsoredmenu float-right'>विज्ञापन</span> </p>",
    "<span class='icon-used-car menusIcon'></span>Used Cars<i data-icon-arrow-left='withoutfill'></i>": "<span class='icon-used-car menusIcon'></span> सेकेंड हैंड कार <i data-icon-arrow-left='withoutfill'></i>",
    "Used Cars": "सेकेंड हैंड कार",
    "<span class='icon-sell-car menusIcon'></span>Sell Car": "<span class='icon-sell-car menusIcon'></span> गाड़ी बेचना",
    "Sell Car": "गाड़ी बेचना",
    "<span class='icon-compare-car menusIcon'></span>Compare Cars": "<span class='icon-compare-car menusIcon'></span> कारों की तुलना करें",
    "<span class='icon-news menusIcon'></span>News & Reviews<i data-icon-arrow-left='withoutfill'></i>": "<span class='icon-news menusIcon'></span> समाचार और समीक्षा <i data-icon-arrow-left='withoutfill'></i>",
    "News & Reviews": "समाचार और समीक्षा",
    "Auto News": "ऑटो समाचार",
    "Write a Review": "एक समीक्षा लिखे",
    "Dealer Solutions": "डीलर समाधान",
    "Car Lease": "कार लीज",
    "Change Language<i data-icon-arrow-left='withoutfill'></i>": "भाषा बदलो <i data-icon-arrow-left='withoutfill'></i>",
    "Change Language": "भाषा बदलो",
    "About CarDekho<i data-icon-arrow-left='withoutfill'></i>": "CarDekho के बारे में <i data-icon-arrow-left='withoutfill'></i>",
    "About CarDekho": "CarDekho के बारे में",
    "About": "के बारे में",
    "Terms & Conditions": "नियम एवं शर्तें",
    "Privacy Policy": "गोपनीयता नीति",
    "FAQs": "पूछे जाने वाले प्रश्न",
    "Feedback": "प्रतिक्रिया",
    "Contact Us": "हमसे संपर्क करें",
    "OVERVIEW": "अवलोकन",
    "About us": "हमारे बारे में",
    "OTHERS": "दूसरों",
    "Trustmarked used cars": "भरोसेमंद इस्तेमाल की गई कारें",
    "Advertise with Us": "हमारे साथ विज्ञापन",
    "Careers": "करियर",
    "Customer Care": "ग्राहक सेवा",
    "CONNECT WITH US": "हमसे जुडे",
    "1800 200 3000 (Toll-Free)": "1800 200 3000 (टोल फ्री)",
    "support@cardekho.com": "support@cardekho.com",
    "Dealer solution": "डीलर समाधान",
    "EXPERIENCE CARDEKHO APP": "अनुभव CARDEKHO एपीपी",
    "India’s #1": "भारत का # 1",
    "Car Sold": "कार बेच दिया",
    "Every 4 minute": "हर 4 मिनट",
    "Stay updated pay less": "अद्यतन वेतन कम रहो",
    "Decode the right car": "सही कार डीकोड करें",
    "Home": "होम",
    "Login": "लॉग इन करें",
    "Popular Categories": "लोकप्रिय श्रेणियां",
    "All Categories": "सब वर्ग",
    "Please Select A Category": "कृपया एक कैटेगरी चयनित करें",
    "Shares": "शेयरों",
    "Share": "शेयर",
    "Search": "खोज",
    "Related Guides": "संबंधित गाइड",
    "Views": "दृश्य",
    "Expected date": "अपेक्षित तारीख",
    "Specs": "ऐनक",
    "Reviews": "समीक्षा",
    "Pictures": "चित्रों",
    "Specifications": "विशेष विवरण",
    "*Estimated Price New Delhi": "* अनुमानित मूल्य नई दिल्ली",
    "Stay Updated. Subscribe to Cardekho News": "आधुनिक जानकारी से परिपूर्ण रहो। कार्डकेहो समाचार की सदस्यता लें",
    "Enter your Email Address": "अपना ईमेल पता दर्ज करें",
    "We'll give you relevant updates": "हम आपको प्रासंगिक अपडेट देंगे",
    "Recommended news for you": "आपके लिए अनुशंसित समाचार",
    "News Cars": "समाचार कारें",
    "You might also be interested in": "आप शायद इसमें रुचि रखते हों",
    "Subscribe Now":"अभी ग्राहक बनें",
    "Expected Launch":"अपेक्षित लॉन्च",
    "Ex-showroom Price in": "पूर्व शोरूम मूल्य में",
    "Estimated Price": "अनुमानित दाम",
    "videos": "वीडियो",
    "video": "वीडियो",
    "Previous Page": "पिछला पृष्ठ",
    "prev": "पिछला",
    "Page": "पृष्ठ",
    "pages": "पृष्ठों",
    "of": "का",
    "Next Page": "अगला पृष्ठ",
    "next": "आगामी",
    "Category": "वर्ग",
    "Select": "चुनते हैं",
    "Select News Category":"समाचार श्रेणी का चयन करें",
    "Similar cars to compare & consider": "तुलना करने और विचार करने के लिए इसी तरह की कारें",
    "All Latest Cars": "सभी नवीनतम कारें",
    "All Upcoming Cars": "सभी आने वाली कारें",
    "All Popular Cars": "सभी लोकप्रिय कारें",
    "Latest Cars": "नवीनतम कारें",
    "Upcoming Cars": "आने वाली कारें",
    "Popular Cars": "लोकप्रिय कारें",
    "NewsDetail": "NewsDetail",
    "January": "जनवरी",
    "February": "फरवरी",
    "March": "मार्च",
    "April": "अप्रैल",
    "May": "मई",
    "June": "जून",
    "July": "जुलाई",
    "August": "अगस्त",
    "September": "सितंबर",
    "October": "अक्टूबर",
    "Novermber": "Novermber",
    "December": "दिसंबर",
    "View": "राय",
    "Offers": "ऑफर",
    "Sponsored": "प्रायोजित",
    "On": "पर",
    "By": "द्वारा",
    "Modified": "संशोधित",
    "Published": "प्रकाशित",
    "Write Comment on": "टिप्पणी लिखें",
    "Write a comment": "टिप्पणी लिखें",
    "VIEW ALL": "सभी को देखें",
    "Live Feeds": "लाइव फीड्स",
    "Published by": "द्वारा प्रकाशित",
    "Chandigarh": "चंडीगढ़",
    "Ghaziabad": "गाज़ियाबाद",
    "Gurgaon": "गुडगाँव",
    "Kochi": "कोच्चि",
    "Lucknow": "लखनऊ",
    "New Delhi": "नई दिल्ली",
    "Noida": "नोएडा",
    "Patna": "पटना",
    "Abohar": "Abohar",
    "Abu Road": "अबू रोड",
    "Addanki": "Addanki",
    "Adilabad": "आदिलाबाद",
    "Adityapur": "Adityapur",
    "Adoni": "अदोनी",
    "Adoor": "अदूर",
    "Agar Malwa": "Agar Malwa",
    "Agartala": "Agartala",
    "Agra": "आगरा",
    "Ahmednagar": "अहमदनगर",
    "Ahwa": "Ahwa",
    "Aizawl": "आइजोल",
    "Ajmer": "अजमेर",
    "Akashiganga": "Akashiganga",
    "Akbarpur": "Akbarpur",
    "Akhnoor": "Akhnoor",
    "Akluj": "Akluj",
    "Akola": "Akola",
    "Alagappapuram": "Alagappapuram",
    "Alamcode": "Alamcode",
    "Alandi": "आलंदी",
    "Alappuzha": "अलाप्पुझा",
    "Alibag": "अलीबाग",
    "Aligarh": "अलीगढ़",
    "Alipore": "अलीपुर",
    "Alipurduar": "Alipurduar",
    "Allagadda": "अल्लागड्डा",
    "Allahabad": "इलाहाबाद",
    "Almora": "अल्मोड़ा",
    "Aluva": "अलुवा",
    "Alwar": "अलवर",
    "Amalapuram": "Amalapuram",
    "Amb": "साथ",
    "Ambajogai": "उन्होंने jogai आयोजित",
    "Ambala": "अंबाला",
    "Ambasamudram": "अम्बसमुद्रम",
    "Ambedkar Nagar": "Ambedkar Nagar",
    "Ambegaon": "Ambegaon",
    "Ambernath": "Ambernath",
    "Ambikapur": "Ambikapur",
    "Amethi": "अमेठी",
    "Amloh": "अमलोह",
    "Amod": "प्रदान की",
    "Amravati": "अमरावती",
    "Amreli": "अमरेली",
    "Amritsar": "अमृतसर",
    "Amroha": "Amroha",
    "Amudalavalasa": "वे कपड़े पहने हुए थे",
    "Anakapalle": "Anakapalle",
    "Anakaputhur": "Anakaputhur",
    "Anand": "आनंद",
    "Anandapur": "Anandapur",
    "Anandpur Sahib": "Anandpur Sahib",
    "Anantapur": "अनंतपुर",
    "Anantnag": "अनंतनाग",
    "Anekal": "Anekal",
    "Angamaly": "अंगमाली",
    "Angul": "अंगुल",
    "Ankleshwar": "अंकलेश्वर",
    "Ankola": "अंकोला",
    "Annur": "Annur",
    "Anpara": "निवेदन करना",
    "Anuppur": "Anuppur",
    "Arakkonam": "अराकोणम",
    "Arambag": "Arambag",
    "Araria": "Araria",
    "Arasaradi": "Arasaradi",
    "Arcot": "अर्काट",
    "Ariyalur": "अरियालुर",
    "Armoor": "Armoor",
    "Arni": "यह",
    "Arrah": "आरा",
    "Arsikere": "Arsikere",
    "Aruppukottai": "Aruppukottai",
    "Arwal": "अरवल",
    "Asansol": "आसनसोल",
    "Ashoknagar": "Ashoknagar",
    "Ashta": "अष्ट",
    "Aska": "एश",
    "Assandh": "Assandh",
    "Athani": "Athani",
    "Athgarh": "Athgarh",
    "Attili": "Attili",
    "Attingal": "Attingal",
    "Attur": "अभिनेता",
    "Auraiya": "Auraiya",
    "Aurangabad": "औरंगाबाद",
    "Aurangabad(bh)": "Aurangabad(bh)",
    "Avadi": "अवादी",
    "Avanigadda": "Avanigadda",
    "Avinashi": "Avinashi",
    "Ayodhya": "अयोध्या",
    "Azamgarh": "Azamgarh",
    "Baddi": "बद्दी",
    "Badlapur": "Badlapur",
    "Bagaha": "Bagaha",
    "Bagalkot": "बागलकोट",
    "Bageshwar": "Bageshwar",
    "Baghpat": "Baghpat",
    "Bagru": "खोदक मशीन",
    "Bahadurgarh": "बहादुरगढ़",
    "Baharagora": "Baharagora",
    "Baharampur": "Baharampur",
    "Bahjoi": "Bahjoi",
    "Bahraich": "Bahraich",
    "Bailhongal": "bailhongal",
    "Baksa": "बक्सा",
    "Bakshi Ka Talab": "बक्षी का तालाब",
    "Balaghat": "Balaghat",
    "Balangir": "Balangir",
    "Balaramapuram": "बलरामपुरम",
    "Balasore": "बालासोर",
    "Balesar": "Balesar",
    "Bali": "बाली",
    "Ballabhgarh": "Ballabhgarh",
    "Ballarpur": "बल्लारपुर",
    "Ballia": "Ballia",
    "Balod": "लहर",
    "Baloda Bazar": "Baloda Bazar",
    "Balotra": "Balotra",
    "Balrampur": "बलरामपुर",
    "Balurghat": "बेलूरघाट",
    "Banaskantha": "बनासकांठा",
    "Banda": "बैंड",
    "Banderdewa": "Banderdewa",
    "Bandipora": "Bandipora",
    "Banga": "ज्वार",
    "Bangaon": "Bangaon",
    "Bangarapet": "Bangarapet",
    "Banka": "बैंक",
    "Bankura": "Bankura",
    "Bansda": "Bansda",
    "Bansi": "बंसी",
    "Banswara": "बांसवाड़ा",
    "Bantwal": "Bantwal",
    "Bapatla": "बापतला",
    "Barabanki": "Barabanki",
    "Baramati": "बारामती",
    "Baramulla": "बारामूला",
    "Baran": "बारिश",
    "Barara": "Barara",
    "Barasat": "Barasat",
    "Barauni": "Barauni",
    "Baraut": "बड़ौत",
    "Bardhaman": "बर्धमान",
    "Bardoli": "बारडोली",
    "Bareilly": "बरेली",
    "Bargarh": "बारगढ़",
    "Barhalganj": "Barhalganj",
    "Baripada": "बारीपदा",
    "Barkakana": "बार्का काना",
    "Barmer": "बाड़मेर",
    "Barnala": "बरनाला",
    "Barpeta": "बारपेटा",
    "Barrackpore": "बैरकपुर",
    "Barsar": "Barsar",
    "Barshi": "रखना",
    "Baruipur": "Baruipur",
    "Barwaha": "Barwaha",
    "Barwala": "Barwala",
    "Barwani": "बड़वानी",
    "Basirhat": "बशीरहाट",
    "Bassi": "नीदरलैंड",
    "Bastar": "काफी होना",
    "Basti": "पूरा करना",
    "Batala": "बटाला",
    "Bathinda": "Bathinda",
    "Bavla": "Bavla",
    "Bayana": "श्रीमती एक",
    "Beawar": "ब्यावर",
    "Beed": "बीड",
    "Begusarai": "बेगूसराय",
    "Behror": "बहरोड़",
    "Beldanga": "Beldanga",
    "Belgaum": "बेलगाम",
    "Bellary": "बेल्लारी",
    "Belthangady": "बेल्तांगढी",
    "Bemetara": "Bemetara",
    "Varanasi": "वाराणसी",
    "Berhampur": "बेरहामपुर",
    "Bettiah": "Bettiah",
    "Betul": "यह सही है",
    "Bhabua": "Bhabua",
    "Bhachau": "भचाऊ",
    "Bhadarwah": "Bhadarwah",
    "Bhadohi": "Bhadohi",
    "Bhadrachalam": "भद्राचलम",
    "Bhadrak": "भद्रक",
    "Bhadravathi": "Bhadravathi",
    "Bhadravati": "भद्रावती",
    "Bhagalpur": "Bhagalpur",
    "Bhalukpong": "Bhalukpong",
    "Bhandara": "Bhandara",
    "Bhanjanagar": "Bhanjanagar",
    "Bhanpuri": "भानपुरी",
    "Bharatpur": "भरतपुर",
    "Bharuch": "भरूच",
    "Bhatapara": "Bhatapara",
    "Bhavani": "भवानी",
    "Bhavnagar": "भावनगर",
    "Bhawanipatna": "Bhawanipatna",
    "Bhayandar": "भयंदर",
    "Bhilai": "Bhilai",
    "Bhilwara": "भीलवाड़ा",
    "Bhimavaram": "Bhimavaram",
    "Bhind": "Bhind",
    "Bhismaknagar": "Bhismaknagar",
    "Bhiwadi": "Bhiwadi",
    "Bhiwandi": "भिवंडी",
    "Bhiwani": "Bhiwani",
    "Bhojpur": "भोजपुर",
    "Bhopal": "भोपाल",
    "Bhopalgarh": "Bhopalgarh",
    "Bhubaneswar": "भुवनेश्वर",
    "Bhuj": "भुज",
    "Bhusawal": "Bhusawal",
    "Bhuvanagiri": "Bhuvanagiri",
    "Biaora": "ब्यावरा",
    "Bicholim": "बिचोलिम",
    "Bidar": "बीदर",
    "Bihar Sharif": "Bihar Sharif",
    "Bihta": "Bihta",
    "Bijapur": "बीजापुर",
    "Bijapur (CH)": "Bijapur (CH)",
    "Bijnor": "Bijnor",
    "Bijolia": "Bijolia",
    "Bijoynagar": "Bijoynagar",
    "Bikaner": "बीकानेर",
    "Bilara": "Bilara",
    "Bilaspur": "Bilaspur",
    "Bilaspur(HP)": "Bilaspur(HP)",
    "Bilimora": "बिलिमोरा",
    "Birbhum": "Birbhum",
    "Bishnupur": "बिश्नुपुर",
    "Bishnupur (WB)": "बिष्णूपुर (डब्ल्यूबी)",
    "Bobbili": "बोब्बिली",
    "Bodeli": "Bodeli",
    "Bodh gaya": "Bodh gaya",
    "Boisar": "Boisar",
    "Bokakhat": "Bokakhat",
    "Bokaro": "बोकारो",
    "Bolpur": "बोलपुर",
    "Bomdila": "बोमडिला",
    "Bongaigaon": "बोंगईगांव",
    "Botad": "ठीक हो",
    "Boudh": "Boudh",
    "Brahmapuri": "ब्रह्मपुरी",
    "Buckinghampet": "Buckinghampet",
    "Budaun": "Budaun",
    "Budgam": "Budgam",
    "Bulandshahr": "Bulandshahr",
    "Buldhana": "Buldhana",
    "Bundi": "बूंदी",
    "Burhanpur": "बुरहानपुर",
    "Buxar": "भाप",
    "Byasanagar": "Byasanagar",
    "Cachar": "कछार",
    "Kozhikode": "कोझिकोड",
    "Canacona": "कानाकोना",
    "Kannur": "कन्नूर",
    "Chaibasa": "Chaibasa",
    "Chakdaha": "Chakdaha",
    "Chakradharpur": "Chakradharpur",
    "Chaksu": "चाकसू",
    "Chakulia": "Chakulia",
    "Chalakudy": "चलाकुडी",
    "Chalisgaon": "Chalisgaon",
    "Chamarajanagar": "Chamarajanagar",
    "Chamba": "चंबा",
    "Chamoli": "Chamoli",
    "Champawat": "Champawat",
    "Champhai": "चम्फाई",
    "Chandauli": "Chandauli",
    "Chandausi": "Chandausi",
    "Chandel": "चंदेल",
    "Chandragiri": "चंद्रगिरी",
    "Chandrakona": "चंद्राकोना",
    "Chandrapur": "चंद्रपुर",
    "Changanassery": "चंगनशेरी",
    "Changaramkulam": "Changaramkulam",
    "Changlang": "चांगलांग",
    "Channapatna": "Channapatna",
    "Charkhi dadri": "Charkhi dadri",
    "Chatra": "Chatra",
    "Chattarpur": "Chattarpur",
    "Chavakkad": "चवक्कड़",
    "Cheeka": "Cheeka",
    "Chengalpattu": "चेंगलपट्टू",
    "Chengannur": "Chengannur",
    "Cherpulassery": "Cherpulassery",
    "Cherthala": "Cherthala",
    "Chhapra": "छपरा",
    "Chhatrapur": "Chhatrapur",
    "Chhindwara": "छिंदवाड़ा",
    "Chikkaballapur": "चिकबलपुर",
    "Chikmagalur": "चिकमंगलूर",
    "Chikodi": "यह ठीक है",
    "Chilakaluripet": "Chilakaluripet",
    "Chinsurah": "Chinsurah",
    "Chintamani": "चिंतामणि",
    "Chiplun": "चिपलुन",
    "Chirala": "चिराला",
    "Chirang": "चिरांग",
    "Chirawa": "Chiran",
    "Chitradurga": "चित्रदुर्ग",
    "Chitrakoot": "Chitrakoot",
    "Chittoor": "चित्तूर",
    "Chittorgarh": "चित्तौड़गढ़",
    "Chodavaram": "Chodavaram",
    "Chomu": "चोमू",
    "Churachandpur": "Churachandpur",
    "Churu": "चुरू",
    "Coimbatore": "कोयंबटूर",
    "Contai": "contai",
    "Cooch Behar": "कूच बिहार",
    "Coonoor": "कुन्नूर",
    "Coorg": "कूर्ग",
    "Cuddalore": "कुड्डालोर",
    "Cuncolim": "Cuncolim",
    "Curchorem": "Curchorem",
    "Cuttack": "कटक",
    "Dabhoi": "दभोई",
    "Dabra": "डबरा",
    "Dadra and Nagar Haveli": "दादरा और नगर हवेली",
    "Dadri": "दादरी",
    "Dahanu": "Dahanu",
    "Dahegam": "Dahegam",
    "Dahod": "दाहोद",
    "Dakshin Dinajpur": "दक्षिण दिनाजपुर",
    "Dakshina Kannada": "दक्षिणी कन्नड़",
    "Dalhousie": "डलहौजी",
    "Dalkhola": "Dalkhola",
    "Dalsingsarai": "कोटिंग्स घाटी अराइ",
    "Daman": "दमन",
    "Damoh": "Damoh",
    "Damtal": "Damtal",
    "Danapur": "Danapur",
    "Dang": "डैंग",
    "Dankuni": "दानकुनी",
    "Dantewada": "दंतेवाड़ा",
    "Dapoli": "दापोली",
    "Darbhanga": "Darbhanga",
    "Dargamitta": "Dargamitta",
    "Darjeeling": "दार्जिलिंग",
    "Darrang": "दरांग",
    "Dasuya": "Dasuya",
    "Datia": "Datia",
    "Daund": "दौंड",
    "Dausa": "दौसा",
    "Davangere": "Davangere",
    "Debagarh": "Debagarh",
    "Deeg": "लोई",
    "Deesa": "देवी",
    "Dehra gopipur": "Dehra gopipur",
    "Dehradun": "देहरादून",
    "Dehri on sone": "Dehri on sone",
    "Deoband": "देवबंद",
    "Deoghar": "देवघर",
    "Deoli": "देवली",
    "Deoria": "Deoria",
    "Depalpur": "देपालपुर",
    "Dera Bassi": "डेरा बास्सी",
    "Devakottai": "देवाकोत्तई",
    "Devanahalli": "देवनहल्ली",
    "Devgadh": "Devgadh",
    "Devgadh Baria": "Devgadh Baria",
    "Devigarh": "Devigarh",
    "Dewas": "देवास",
    "Dhalai": "धलाई",
    "Dhampur": "धामपुर",
    "Dhamtari": "Dhamtari",
    "Dhanbad": "धनबाद",
    "Dhar": "धार",
    "Dharampur": "धरमपुर",
    "Dharamshala": "धर्मशाला",
    "Dharapuram": "धारापुरम",
    "Dharbandora": "Dharbandora",
    "Dharmanagar": "Dharmanagar",
    "Dharmapuri": "धर्मपुरी",
    "Dharmavaram": "धर्मावरम",
    "Dharuhera": "धारूहेड़ा",
    "Dharwad": "धारवाड़",
    "Dhemaji": "धेमाजी",
    "Dhenkanal": "Dhenkanal",
    "Dholka": "मैदान में",
    "Dholpur": "Dholpur",
    "Dhrangadhra": "ध्रांगधरा",
    "Dhubri": "धुबरी",
    "Dhubulia": "Dhubulia",
    "Dhule": "धुले",
    "Dhuri": "Dhuri",
    "Diamond Harbour": "डायमंड हार्बर",
    "Dibang Valley": "डिबांग घाटी",
    "Dibrugarh": "डिब्रूगढ़",
    "Didwana": "Didwana",
    "Digboi": "डिगबोई",
    "Diglipur": "दिगलिपुर",
    "Dima Hasao": "दीमा हसाओ",
    "Dimapur": "Dimapur",
    "Dindigul": "डिंडीगुल",
    "Dindori": "डिंडोरी",
    "Dindori (MH)": "Dindori (MH)",
    "Diphu": "दिफू",
    "Dispur": "दिसपुर",
    "Diu": "कहते हैं",
    "Doda": "डोडा",
    "Dombivli": "Dombivli",
    "Doraha": "Doraha",
    "Duliajan": "दुलियाजान",
    "Dumka": "दुमका",
    "Dungarpur": "डूंगरपुर",
    "Durg": "Durg",
    "Durgapur": "दुर्गापुर",
    "East Champaran": "East Champaran",
    "East Garo Hills": "पूर्वी गारो हिल्स",
    "East Godavari": "पूर्वी गोदावरी",
    "East Kameng": "पूर्वी कामेंग",
    "East Khasi Hills": "पूर्वी खासी हिल्स",
    "East Siang": "पूर्वी दोपहर",
    "East Sikkim": "पूर्वी सिक्किम",
    "East Singhbhum": "East Singhbhum",
    "Edapal": "Edapal",
    "Ellenabad": "ऐलनाबाद",
    "Eluru": "एलुरु",
    "Ernakulam": "एर्नाकुलम",
    "Erode": "इरोड",
    "Etah": "एटा",
    "Etawah": "इटावा",
    "Faizabad": "Faizabad",
    "Falna": "पूर्ण",
    "Faridabad": "फरीदाबाद",
    "Faridkot": "Faridkot",
    "Farrukhabad": "Farrukhabad",
    "Fatehabad": "फतेहाबाद",
    "Fatehgarh": "फतेहगढ़",
    "Fatehgarh Sahib": "Fatehgarh Sahib",
    "Fatehnagar": "Fatehnagar",
    "Fatehpur": "Fatehpur",
    "Fazilka": "Fazilka",
    "Firozabad": "Firozabad",
    "Firozpur": "Firozpur",
    "Gadag": "गडग",
    "Gadarwara": "Gadarwara",
    "Gadchiroli": "गडचिरोली",
    "Gadhinglaj": "Gadhinglaj",
    "Gadwal": "गडवाल",
    "Gajapati": "Gajapati",
    "Gajraula": "Gajraula",
    "Gajuwaka": "गजुवाका",
    "Ganaur": "जाओ",
    "Ganderbal": "गांदरबल",
    "Gandhidham": "Gandhidham",
    "Gandhinagar": "गांधीनगर",
    "Gangapur Rs": "गंगापुर रु",
    "Gangavati": "गंगावती",
    "Gangtok": "गंगटोक",
    "Ganj Basoda": "Ganj Basoda",
    "Ganjam": "गंजम",
    "Garhshanker": "Garhshanker",
    "Garhwa": "Garhwa",
    "Gariaband": "Gariaband",
    "Gauriganj": "Gauriganj",
    "Gautam Buddha Nagar": "Gautam Buddha Nagar",
    "Gaya": "शैली",
    "Gezing": "gezing",
    "Gharaunda": "Gharaunda",
    "Ghatal": "Ghatal",
    "Ghatampur": "Ghatampur",
    "Ghatsila": "Ghatsila",
    "Ghazipur": "Ghazipur",
    "Giridih": "Giridih",
    "Goa": "गोवा",
    "Goalpara": "गोलपाड़ा",
    "Gobichettipalayam": "Gobichettipalayam",
    "Gobindpur": "गोबिंदपुर",
    "Gobindpur (JH)": "गोबिंदपुर (जेएच)",
    "Godda": "नई",
    "Godhra": "गोधरा",
    "Gohana": "Gohana",
    "Gokak": "गोकक",
    "Golaghat": "गोलाघाट",
    "Gomoh": "Gomoh",
    "Gonda": "गोंडा",
    "Gondal": "गोंडल",
    "Gondia": "गोंदिया",
    "Gonikoppal": "Gonikoppal",
    "Gopalganj": "गोपालगंज",
    "Gopeshwar": "Gopeshwar",
    "Gorakhpur": "गोरखपुर",
    "Gossaigaon": "Gossaigaon",
    "Greater Noida": "ग्रेटर नोएडा",
    "Gudalur": "Gudalur",
    "Gudivada": "गुडिवाडा",
    "Gudur": "गुडूर",
    "Gulbarga": "गुलबर्गा",
    "Gulmarg": "गुलमर्ग",
    "Gumla": "Gumla",
    "Guna": "उपयोग के लिए",
    "Guntakal": "Guntakal",
    "Guntur": "गड़गड़ाहट",
    "Gurdaspur": "गुरदासपुर",
    "Guruvayoor": "गुरुवायुर",
    "Guwahati": "गुवाहाटी",
    "Gwalior": "ग्वालियर",
    "Haflong": "हाफलोंग",
    "Hailakandi": "हैलाकांडी",
    "Hajipur": "Hajipur",
    "Hajo": "हाजो",
    "Haldia": "हल्दिया",
    "Haldwani": "Haldwani",
    "Halol": "बल्ला",
    "Hamirpur(UP)": "Hamirpur(UP)",
    "Hamirpur(hp)": "Hamirpur(hp)",
    "Hanamkonda": "Hanamkonda",
    "Hansi": "हांसी",
    "Hanumangarh": "Hanumangarh",
    "Hapur": "खुला",
    "Harda": "हरदा",
    "Hardoi": "Hardoi",
    "Haridwar": "हरिद्वार",
    "Harihar": "हरिहर",
    "Harpanahalli": "वीणा घाटा",
    "Harur": "Harur",
    "Hassan": "हसन",
    "Hathras": "Hathras",
    "Haveri": "हावेरी",
    "Hazaribagh": "हजारीबाग",
    "Hilsa": "हिलसा",
    "Himatnagar": "हिम्मतनगर",
    "Hindaun": "Hindaun",
    "Hindupur": "Hindupur",
    "Hingoli": "हिंगोली",
    "Hisar": "किले",
    "Hodal": "Hodal",
    "Hooghly": "हुगली",
    "Hoshangabad": "Hoshangabad",
    "Hoshiarpur": "होशियारपुर",
    "Hoskote": "होसकोटे",
    "Hospet": "होसपेट",
    "Hosur": "होसुर",
    "Howrah": "हावड़ा",
    "Hubli": "हुबली",
    "Hukkeri": "Hukkeri",
    "Huzurabad": "Huzurabad",
    "Ibrahimpatnam": "इब्राहिमपत्तनम",
    "Ichalkaranji": "Ichalkaranji",
    "Idar": "Idar",
    "Idukki": "इडुक्की",
    "Imphal": "इंफाल",
    "Indapur": "Indapur",
    "Indi": "अब",
    "Indore": "इंदौर",
    "Irinjalakuda": "Irinjalakuda",
    "Islampur (WB)": "इस्लामपुर (डब्ल्यूबी)",
    "Itanagar": "ईटानगर",
    "Itarsi": "Itarsi",
    "Jabalpur": "जबलपुर",
    "Jadcherla": "Jadcherla",
    "Jagadhri": "Jagadhri",
    "Jagatsinghpur": "Jagatsinghpur",
    "Jagdalpur": "जगदलपुर",
    "Jagdishpur": "Jagdishpur",
    "Jaggaiahpeta": "Jaggaiahpeta",
    "Jagiroad": "Jagiroad",
    "Jagraon": "जगराओं",
    "Jagtial": "Jagtial",
    "Jaigaon": "Jaigaon",
    "Jaintia Hills": "जेंतिया हिल्स",
    "Jaisalmer": "जैसलमेर",
    "Jaitaran": "Jaitaran",
    "Jaitu": "Jaitu",
    "Jajpur": "Jajpur",
    "Jalalabad": "जलालाबाद",
    "Jalandhar": "जालंधर",
    "Jalaun": "Jalaun",
    "Jaleswar": "जलेश्वर",
    "Jalgaon": "जलगांव",
    "Jalna": "जलना",
    "Jalore": "Jalore",
    "Jalpaiguri": "जलपाईगुड़ी",
    "Jam Jodhpur": "Jam Jodhpur",
    "Jamakhandi": "Jamakhandi",
    "Jammu": "जम्मू",
    "Jamnagar": "जामनगर",
    "Jamshedpur": "जमशेदपुर",
    "Jamtara": "Jamtara",
    "Jamui": "Jamui",
    "Jandiala guru": "Jandiala guru",
    "Jangaon": "जनगांव",
    "Jangareddygudem": "Jangareddygudem",
    "Janjgir-Champa": "Janjgir-Champa",
    "Jasdan": "Jasdan",
    "Jashpur": "Jashpur",
    "Jassur": "Jassur",
    "Jaunpur": "Jaunpur",
    "Jaysingpur": "Jaysingpur",
    "Jehanabad": "Jehanabad",
    "Jetpur": "जेतपुर",
    "Jeypore": "जयपोर",
    "Jhabua": "Jhabua",
    "Jhajjar": "Jhajjar",
    "Jhalawar": "झालावाड़",
    "Jhansi": "Jhansi",
    "Jharsuguda": "झारसुगुडा",
    "Jhunjhunu": "Jhunjhunu",
    "Jind": "तड़प",
    "Jobner": "जोबनेर",
    "Joda": "Joda",
    "Jodhpur": "जोधपुर",
    "Jorabat": "Korabav",
    "Jorethang": "Jorethang",
    "Jorhat": "Jorhat",
    "Jowai": "जोवाई",
    "Joya": "गहना",
    "Junagadh": "जूनागढ़",
    "Kabirdham": "Kabirdham",
    "Kachchh": "कच्छ",
    "Kadapa": "कडपा",
    "Kadi": "कार्ड",
    "Kadiri": "अधिक",
    "Kadur": "कडुर",
    "Kahalgaon": "Kahalgaon",
    "Kaipamangalam": "Kaipamangalam",
    "Kaithal": "Kaithal",
    "Kakinada": "काकीनाडा",
    "Kalahandi": "कालाहांडी",
    "Kalamassery": "Kalamassery",
    "Kalka": "कालका",
    "Kallambalam": "Kallambalam",
    "Kalol": "कलोल",
    "Kalpetta": "कलपेट्टा",
    "Kalyan": "कल्याण",
    "Kalyani": "कल्याणी",
    "Kamareddy": "Kamareddy",
    "Kamrup": "कामरूप",
    "Kanchipuram": "कांचीपुरम",
    "Kandhamal": "कंधमाल",
    "Kandi": "कंडी",
    "Kandukur": "Kandukur",
    "Kangayam": "Kangayam",
    "Kangra": "कांगड़ा",
    "Kanhangad": "Kanhangad",
    "Kanigiri": "Kanigiri",
    "Kanjirappally": "कन्जिराप्पल्ली",
    "Kankavli": "Kankavli",
    "Kanker": "कैंसर",
    "Kankroli": "Kankroli",
    "Kannauj": "Kannauj",
    "Kanpur": "कानपुर",
    "Kanpur Dehat": "Kanpur Dehat",
    "Kanyakumari": "Kanyakumari",
    "Kapadvanj": "Kapadvanj",
    "Kapurthala": "कपूरथला",
    "Karad": "कराड",
    "Karaikal": "कराईकल",
    "Karaikudi": "कराइकुडी",
    "Karauli": "करौली",
    "Karbi Anglong": "करबी Anglong",
    "Kargil": "कारगिल",
    "Karikkad": "Karikkad",
    "Karimganj": "असम",
    "Karimnagar": "करीमनगर",
    "Karjan": "पशु",
    "Karjat": "कर्जत",
    "Karkala": "करकला",
    "Karnal": "Karnal",
    "Karunagappally": "Karunagappally",
    "Karur": "करूर",
    "Karwar": "कारवार",
    "Kasaragod": "कासरगोड",
    "Kasganj": "Kasganj",
    "Kashipur": "Kashipur",
    "Kathua": "Kathua",
    "Katihar": "Katihar",
    "Katni": "Katni",
    "Katpadi": "Katpadi",
    "Kattappana": "कट्टाप्पना",
    "Katwa": "कटवा",
    "Kaushambi": "Kaushambi",
    "Kavali": "कवाली",
    "Kavaratti": "Kavaratti",
    "Kavathe-Mahankal": "Kavathe-Mahankal",
    "Kawardha": "कवर्धा",
    "Kayamkulam": "कायमकुलम",
    "Kekri": "Kekri",
    "Kelambakkam": "Kelambakkam",
    "Kendrapara": "Kendrapara",
    "Kendujhar": "Kendujhar",
    "Kengeri": "Kengeri",
    "Kesarapalle": "Kesarapalle",
    "Khagaria": "खगरिया",
    "Khair": "खैर",
    "Khalilabad": "Khalilabad",
    "Khambhalia": "Khambhalia",
    "Khambhat": "खंभात",
    "Khamgaon": "Khamgaon",
    "Khammam": "खम्मम",
    "Khandala": "खंडाला",
    "Khandwa": "Khandwa",
    "Khanna": "खन्ना",
    "Kharagpur": "खड़गपुर",
    "Kharar": "खरड़",
    "Kharghar": "Kharghar",
    "Khargone": "Khargone",
    "Khatima": "Khatima",
    "Kheda": "Kheda",
    "Kheralu": "Kheralu",
    "Khliehriat": "Khliehriat",
    "Khopoli": "खोपोली",
    "Khordha": "Khordha",
    "Khowai": "Khowai",
    "Khunti": "खूंटी",
    "Khurja": "Khurja",
    "Kinnaur": "किन्नौर",
    "Kiphire": "किफायर",
    "Kiraoli": "किरौली",
    "Kishanganj": "Kishanganj",
    "Kishangarh": "किशनगढ़",
    "Kochas": "Loverboy",
    "Kodagu": "कोडागू",
    "Koderma": "Koderma",
    "Kodungallur": "कोडुन्गल्लुर",
    "Kohima": "कोहिमा",
    "Kokrajhar": "Kokrajhar",
    "Kolar": "कोलार",
    "Kolasib": "कोलासिब",
    "Kolhapur": "कोल्हापुर",
    "Kollam": "कोल्लम",
    "Kollegal": "कोल्लेगल",
    "Konch": "Konch",
    "Kondagaon": "Kondagaon",
    "Konnagar": "Konnagar",
    "Koothattukulam": "कूथाटुकुलम",
    "Koppa": "लकडी की डलिया",
    "Koppal": "कोप्पल",
    "Koraput": "कोरापुट",
    "Koratty": "Koratty",
    "Korba": "पतवार",
    "Koriya": "Koriya",
    "Kosamba": "Kosamba",
    "Kota": "शहर",
    "Kotagiri": "कोटागिरी",
    "Kotdwara": "Kotdwara",
    "Kothagudem": "Kothagudem",
    "Kothamangalam": "कोठामंगलम",
    "Kothapeta": "Kothapeta",
    "Kotma": "Kotma",
    "Kotputli": "Kotputli",
    "Kottakkal": "कोट्टाकल",
    "Kottarakkara": "कोट्टाराक्कारा",
    "Kottayam": "कोट्टायम",
    "Kovilpatti": "कोविलपट्टी",
    "Koyilandy": "Koyilandy",
    "Kozhencherry": "Kozhencherry",
    "Krishna": "कृष्णा",
    "Krishnagiri": "कृष्णागिरी",
    "Krishnanagar": "कृष्णनगर",
    "Kuchaman City": "कुचमन सिटी",
    "Kudal": "कुदाल",
    "Kudra": "Kudra",
    "Kulgam": "कुलगाम",
    "Kulithalai": "Kulithalai",
    "Kullu": "कुल्लू",
    "Kumbakonam": "कुंभकोणम",
    "Kumta": "कुमटा",
    "Kundapur": "कुंदापुर",
    "Kundli": "Kundli",
    "Kunigal": "कुनिगल",
    "Kunjaban": "Kunjaban",
    "Kunnamkulam": "कुन्नम्कुलम",
    "Kupwara": "Kupwara",
    "Kurnool": "कुरनूल",
    "Kurukshetra": "Kurukshetra",
    "Kurung Kumey": "कुरुंग कुमी",
    "Kushalanagar": "Kushalanagar",
    "Kushinagar": "Kushinagar",
    "Ladakh": "लद्दाख",
    "Lahaul And Spiti": "लाहौल और स्पीति",
    "Laheriasarai": "Laheriasarai",
    "Lakhimpur Kheri": "Lakhimpur Kheri",
    "Lakhimpur(Assam)": "Lakhimpur(Assam)",
    "Lakhisarai": "लखीसराय",
    "Lakshadweep": "लक्षद्वीप",
    "Lalganj": "Lalganj",
    "Lalgudi": "लालगुडी",
    "Lalitpur": "Lalitpur",
    "Lansdowne": "लैंसडाउन",
    "Latehar": "Latehar",
    "Latur": "आलसी",
    "Lawngtlai": "Lawngtlai",
    "Leh": "लेह",
    "Lohardaga": "Lohardaga",
    "Lohit": "लोहित",
    "Longleng": "लोंगलेंग",
    "Lower Dibang Valley": "लोअर डिबांग घाटी",
    "Lower Subansiri": "निचला उप-वर्गीकरण",
    "Ludhiana": "लुधियाना",
    "Lunglei": "Lunglei",
    "Luni": "सोमवार",
    "Machhiwara": "Machhiwara",
    "Machilipatnam": "मछलीपट्टनम",
    "Madanapalle": "मदनपल्ली",
    "Madanganj": "Madanganj",
    "Madhapur": "Madhapur",
    "Madhepura": "Madhepura",
    "Madhubani": "मधुबनी",
    "Madhyamgram": "Madhyamgram",
    "Madikeri": "Madikeri",
    "Madurai": "मदुरै",
    "Mahabaleshwar": "महाबलेश्वर",
    "Mahabubabad": "Mahabubabad",
    "Mahad": "धन्यवाद",
    "Maharajganj": "Maharajganj",
    "Mahasamund": "Mahasamund",
    "Mahbubnagar": "महबूबनगर",
    "Mahe": "माहे",
    "Mahendragarh": "Mahendragarh",
    "Mahilpur": "Mahilpur",
    "Mahisagar": "Mahisagar",
    "Mahmudabad": "महमूदाबाद",
    "Mahoba": "Mahoba",
    "Mahuva": "महुवा",
    "Maihar": "मैहर",
    "Mailatti": "रैकेट",
    "Mainpuri": "Mainpuri",
    "Majuli": "जुलाई",
    "Makrana": "Makrana",
    "Malappuram": "मलप्पुरम",
    "Malbazar": "Malbazar",
    "Maldah": "Maldah",
    "Malegaon": "मालेगांव",
    "Malinithan": "मालिनीथन",
    "Malkangiri": "Malkangiri",
    "Mallappally": "Mallappally",
    "Malout": "मलोट",
    "Malvan": "मालवन",
    "Mamit": "माँ",
    "Manali": "मनाली",
    "Manamadurai": "मनमदुरै",
    "Mancherial": "Mancherial",
    "Mandal": "Mandal",
    "Mandapeta": "मंडपेटा",
    "Margao": "मार्गो",
    "Mandi": "स्नान करो",
    "Mandi Gobindgarh": "Mandi Gobindgarh",
    "Mandi dabwali": "Mandi dabwali",
    "Mandla": "Mandla",
    "Mandsaur": "Mandsaur",
    "Mandvi (Kachchh)": "मांडवी (कच्छ)",
    "Mandya": "मंड्या",
    "Manendragarh": "Manendragarh",
    "Manesar": "मानेसर",
    "Mangalagiri": "मंगलगिरी",
    "Mangaldai": "Mangaldai",
    "Mangalore": "मंगलौर",
    "Mangan": "मैंगनीज",
    "Manipal": "मणिपाल",
    "Manjeri": "मंजेरी",
    "Mannargudi": "मन्नारगुडी",
    "Mannarkkad": "Mannarkkad",
    "Mansa": "Mansa",
    "Mansa (GJ)": "Mansa (GJ)",
    "Mapusa": "मापुसा",
    "Marhowrah": "Marhowrah",
    "Markapur": "मरकापुर",
    "Marthandam": "Marthandam",
    "Marwar": "मारवाड़",
    "Matheran": "माथेरान",
    "Mathura": "मथुरा",
    "Mau": "करना चाहते हैं",
    "Mavelikara": "मवेलीकारा",
    "Mavli": "Mavli",
    "Mayabunder": "मायाबंदर",
    "Mayiladuthurai": "यह मुझे खर्च होगा",
    "Mayurbhanj": "Mayurbhanj",
    "Medak District": "मेदक जिला",
    "Medininagar": "Medininagar",
    "Meerut": "मेरठ",
    "Meham": "Meham",
    "Mehsana": "मेहसाणा",
    "Melakaveri": "Melakaveri",
    "Melur": "चमेली",
    "Merta city": "मेर्ता शहर",
    "Metpally": "Metpally",
    "Mettupalayam": "मेट्टुपालयम",
    "Mewat": "Mewat",
    "Mhow": "महू",
    "Midnapore": "मिदनापुर",
    "Mira Road": "मीरा रोड",
    "Miraj": "मिराज",
    "Miryalaguda": "Miryalaguda",
    "Mirzapur": "Mirzapur",
    "Mittapalli": "Mittapalli",
    "Modasa": "मोडासा",
    "Modinagar": "Modinagar",
    "Moga": "मोगा",
    "Mohali": "मोहाली",
    "Mohania": "मोहनिया",
    "Mokokchung": "मोकोकचुंग",
    "Mon": "मेरी",
    "Moodabidri": "मुदबिद्री",
    "Moosapet": "Moosapet",
    "Moradabad": "मुरादाबाद",
    "Morbi": "फुटबॉल",
    "Morena": "श्यामला",
    "Morigaon": "मोरीगांव",
    "Moti Khavdi": "Moti Khavdi",
    "Motihari": "मोतिहारी",
    "Mount Abu": "माउंट आबू",
    "Mukerian": "Mukerian",
    "Mulki": "संपत्ति",
    "Mundra": "मुंद्रा",
    "Mungeli": "Mungeli",
    "Munger": "मुंगेर",
    "Murgud": "विकृतियों",
    "Murshidabad": "मुर्शिदाबाद",
    "Murthal": "मुरथल",
    "Murudeshwara": "मुरुदेश्वर",
    "Musabani": "Musabani",
    "Muttom": "मूर्ख",
    "Muvattupuzha": "मुवात्तुपूजा",
    "Muzaffarnagar": "Muzaffarnagar",
    "Muzaffarpur": "Muzaffarpur",
    "Mysore": "मैसूर",
    "Nabadwip": "नवद्वीप",
    "Nabarangpur": "Nabarangpur",
    "Nabha": "Nabha",
    "Nadia": "नादिया",
    "Nadiad": "नाडियाड",
    "Nagaon": "नगांव",
    "Nagapattinam": "नागपट्टिनम",
    "Nagarkurnool": "नगरकुरनूल",
    "Nagaur": "नागौर",
    "Nagercoil": "नागरकोइल",
    "Nagoa": "नागोआ",
    "Nagole": "Nagole",
    "Nagpur": "नागपुर",
    "Nagrota": "Nagrota",
    "Nahan": "चमड़ा",
    "Naharlagun": "Naharlagun",
    "Naihati": "नैहाटी",
    "Nainital": "नैनीताल",
    "Nakodar": "नकोदर",
    "Nakur": "Nakur",
    "Nalagarh": "नालागढ़",
    "Nalanda": "नालंदा",
    "Nalbari": "नलबाड़ी",
    "Nalgonda": "नलगोंडा",
    "Nallapadu": "Nallapadu",
    "Namakkal": "नमक्कल",
    "Nanded": "नांदेड़",
    "Nandurbar": "नंदुरबार",
    "Nandyal": "नांदयाल",
    "Nangal": "नांगल",
    "Nanjangud": "नंजनगुड",
    "Naraingarh": "Naraingarh",
    "Narasaraopet": "Narasaraopet",
    "Narayangaon": "Narayangaon",
    "Narayanpur": "नारायणपुर",
    "Narayanpur (CH)": "Narayanpur (CH)",
    "Nargund": "Nargund",
    "Narmada": "Narmada",
    "Narnaul": "Narnaul",
    "Narsapur": "Narsapur",
    "Narsinghpur": "Narsinghpur",
    "Narsipatnam": "Narsipatnam",
    "Narwana": "Narwana",
    "Nashik": "नासिक",
    "Nasirabad": "नसीराबाद",
    "Nathdwara": "Nathdwara",
    "Naugarh": "Naugarh",
    "Navi Mumbai": "Navi Mumbai",
    "Navsari": "नवसारी",
    "Nawabganj": "Nawabganj",
    "Nawada": "Nawada",
    "Nawanshahr": "नवांशहर",
    "Nayagarh": "Nayagarh",
    "Nedumangad": "नेदुमनगड",
    "Neem-Ka-Thana": "Neem-Ka-Thana",
    "Neemrana": "नीमराना",
    "Neemuch": "Neemuch",
    "Nellore": "नेल्लोर",
    "New Town": "नया शहर",
    "Newai": "निवाई",
    "Neyveli": "नेवेली",
    "Neyyattinkara": "Neyyattinkara",
    "Nicobar Islands": "निकोबार द्वीप समूह",
    "Nihal Singh Wala": "निहाल सिंह वाला",
    "Nilambur": "निलाम्बुर",
    "Nilamel": "Nilamel",
    "Nimbahera": "Nimbahera",
    "Nirjuli": "Nirjuli",
    "Nirmal": "Nirmal",
    "Nizamabad": "निजामाबाद",
    "Nohar": "नोहर",
    "Nokha": "Nokha",
    "Nongpoh": "नोंगपोह",
    "Nongstoin": "Nongstoin",
    "North 24 Parganas": "उत्तर 24 परगना",
    "North Tripura": "उत्तर त्रिपुरा",
    "North lakhimpur": "North lakhimpur",
    "Nowgong": "नौगांव",
    "Nuapada": "Nuapada",
    "Nuh": "नूह",
    "Nurpur": "नूरपुर",
    "Nuvem": "बादल",
    "Nuzvid": "नुज्विद",
    "Olavakkode": "Olavakkode",
    "Olpad": "Olpad",
    "Omalur": "Omalur",
    "Ongole": "ओंगोल",
    "Ooty": "ऊटी",
    "Orai": "मौसम",
    "Osian": "ओसियां",
    "Osmanabad": "उस्मानाबाद",
    "Ottapalam": "Ottapalam",
    "Padra": "बेंच",
    "Padrauna": "Padrauna",
    "Pahalgam": "Pahalgam",
    "Pakhanjore": "Pakhanjore",
    "Pakur": "Pakur",
    "Pala": "बेलचा",
    "Palakkad": "पलक्कड़",
    "Palakol": "कुल्हाड़ी",
    "Palamaner": "Palamaner",
    "Palampur": "पालमपुर",
    "Palamu": "उपाधि",
    "Palani": "पलानी",
    "Palanpur": "पालनपुर",
    "Palayamkottai": "Palayamkottai",
    "Palghar": "Palghar",
    "Pali": "पाली",
    "Palladam": "पल्लादम",
    "Palsana": "Palsana",
    "Palus": "आलीशान",
    "Palwal": "Palwal",
    "Panagarh": "Panagarh",
    "Panaji": "पणजी",
    "Panchkula": "पंचकुला",
    "Panchmahal": "पंचमहल",
    "Pandharpur": "पंढरपुर",
    "Panipat": "Panipat",
    "Panna": "रखो",
    "Panoor": "panoor",
    "Panvel": "पनवेल",
    "Paonta sahib": "पोंटा साहिब",
    "Papanasam": "Papanasam",
    "Papum Pare": "पापम पारे",
    "Paralakhemundi": "Paralakhemundi",
    "Paramakudi": "Paramakudi",
    "Parassala": "Parassala",
    "Paratwada": "Paratwada",
    "Paravur": "पारावुर",
    "Parbhani": "परभनी",
    "Parkal": "Parkal",
    "Parli": "परली",
    "Parvathipuram": "Parvathipuram",
    "Paschim Medinipur": "Paschim Medinipur",
    "Pasighat": "Pasighat",
    "Patamda": "यह मेरी जेब में है",
    "Patan": "पाटन",
    "Patancheru": "Patancheru",
    "Patas": "पिंस",
    "Pataudi": "पटौदी",
    "Pathanamthitta": "पथानामथिट्टा",
    "Pathankot": "पठानकोट",
    "Patiala": "पटियाला",
    "Patran": "पैतृक",
    "Pattambi": "पट्टाम्बि",
    "Patti": "पट्टी",
    "Pattukkottai": "पत्तुकोत्तई",
    "Pauri": "Pauri",
    "Payyanur": "Payyanur",
    "Peddapalli": "पेद्दापल्ली",
    "Pehowa": "Pehowa",
    "Pelling": "पेलिंग",
    "Pen": "कलम",
    "Perambalur": "पेरम्बलुर",
    "Perambra": "Perambra",
    "Peren": "रहिला",
    "Perinthalmanna": "पेरिन्तल्मन्न",
    "Periyakulam": "पेरियाकुलम",
    "Perumbavoor": "Perumbavoor",
    "Phagwara": "फगवाड़ा",
    "Phalodi": "Phalodi",
    "Phaltan": "फलटन",
    "Phek": "Phek",
    "Phillaur": "Phillaur",
    "Phulbani": "Phulbani",
    "Phusro": "फुसरो",
    "Pilibhit": "Pilibhit",
    "Pimpri chinchwad": "पिंपरी चिंचवाड़",
    "Piparcity": "Piparcity",
    "Piravom": "Piravom",
    "Pithoragarh": "Pithoragarh",
    "Pohir": "Pohir",
    "Pollachi": "पोलाची",
    "Ponda": "पोंडा",
    "Pondicherry": "पांडिचेरी",
    "Ponnani": "पोन्नानी",
    "Ponneri": "Ponneri",
    "Poonamallee": "Poonamallee",
    "Poonch": "पूंछ",
    "Porbandar": "पोरबंदर",
    "Port Blair": "पोर्ट ब्लेयर",
    "Porvorim": "पोरवोरिम",
    "Prakasam": "प्रकाशम",
    "Prantij": "Prantij",
    "Pratapgarh": "Pratapgarh",
    "Pratapgarh(RJ)": "Pratapgarh(RJ)",
    "Proddatur": "प्रोद्दातुर",
    "Pudukkottai": "पुदुक्कोट्टई",
    "Pulwama": "पुलवामा",
    "Punalur": "Punalur",
    "Purba Medinipur": "पूरब मेदिनीपुर",
    "Puri": "Puri",
    "Purnia": "पूर्णिया",
    "Purulia": "पुरुलिया",
    "Puttur": "पुत्तूर",
    "Radaur": "Radaur",
    "Radhakishorepur": "Radhakishorepur",
    "Raebareli": "Raebareli",
    "Raghunathganj": "Raghunathganj",
    "Rahata": "कोई पैसा नहीं",
    "Rahuri": "राहुरी",
    "Raibag": "Raibag",
    "Raichur": "रायचूर",
    "Raigad": "रायगढ़",
    "Raiganj": "Raiganj",
    "Raigarh": "रायगढ़",
    "Raikot": "Raikes",
    "Raipur": "रायपुर",
    "Rairangpur": "Rairangpur",
    "Raisen": "Raisen",
    "Rajahmundry": "राजमुंदरी",
    "Rajampet": "राजमपेट",
    "Rajapalayam": "राजपालयम",
    "Rajapur": "राजापुर",
    "Rajauri": "Rajauri",
    "Rajgarh": "Rajgarh",
    "Rajgarh (RJ)": "Rajgarh (RJ)",
    "Rajim": "Rajim",
    "Rajkot": "राजकोट",
    "Rajnagar": "राजनगर",
    "Rajnandgaon": "Rajnandgaon",
    "Rajpardi": "Rajpardi",
    "Rajpipla": "राजपिपला",
    "Rajpura": "Rajpura",
    "Rajsamand": "राजसमंद",
    "Ramachandrapuram": "रामचंद्रपुरम",
    "Ramagundam": "रामगुंडम",
    "Ramanagara": "रामनगर",
    "Ramanathapuram": "रामनाथपुरम",
    "Ramanattukara": "Ramanattukara",
    "Ramanujganj": "Ramanujganj",
    "Ramapuram": "Ramapuram",
    "Ramdurg": "Ramdurg",
    "Ramganj Mandi": "Ramganj Mandi",
    "Ramgarh": "रामगढ़",
    "Ramnagar": "Ramnagar",
    "Rampur": "रामपुर",
    "Rampur Bushahr": "Rampur Bushahr",
    "Rampura Phul": "Rampura Phul",
    "Rampurhat": "रामपुरहाट",
    "Ranaghat": "Ranaghat",
    "Ranbir Singh Pura": "Ranbir Singh Pura",
    "Ranchi": "रांची",
    "Ranebennuru": "Ranebennuru",
    "Ranga reddy": "रेड्डी क्रोध",
    "Rangat": "रंगत",
    "Rani": "रानी",
    "Raniganj": "रानीगंज",
    "Ranikhet": "रानीखेत",
    "Ranipet": "रानीपेट",
    "Ranni": "Ranni",
    "Rasra": "Rasra",
    "Ratangarh": "Ratangarh",
    "Rath": "अधिक तत्पर",
    "Ratlam": "Ratlam",
    "Ratnagiri": "रत्नागिरी",
    "Raver": "होमोसेक्सुअल",
    "Rawatbhata": "Rawatbhata",
    "Rawatsar": "Rawatsar",
    "Rayadurg": "Rayadurg",
    "Rayagada": "रायगढ़",
    "Razole": "Razol",
    "Reckong Peo": "रेकोंग पीओ",
    "Red hills": "लाल पहाड़ियाँ",
    "Renukoot": "रेणुकूट",
    "Repalle": "Repalle",
    "Rewa": "वैध",
    "Rewari": "रेवाड़ी",
    "Ri Bhoi": "री भोई",
    "Rishikesh": "ऋषिकेश",
    "Robertsganj": "रोबेर्त्स्गंज",
    "Rohru": "रोहड़ू",
    "Rohtak": "Rohtak",
    "Rohtas": "रोहतास",
    "Roorkee": "रुड़की",
    "Rourkela": "राउरकेला",
    "Rudraprayag": "रुद्रप्रयाग",
    "Rudrapur": "रुद्रपुर",
    "Rupnagar": "रूपनगर",
    "Rupnarayanpur": "Rupnarayanpur",
    "Sabarkantha": "साबरकांठा",
    "Sadabad": "Sadabad",
    "Sadasivpet": "Sadasivpet",
    "Safidon": "Safidon",
    "Sagar": "सागर",
    "Sagara": "सगर",
    "Sagwara": "मुझे खेद है",
    "Saharanpur (UP)": "सहारनपुर (यूपी)",
    "Saharsa": "Saharsa",
    "Sahaswan": "Sahaswan",
    "Sahibabad": "Sahibabad",
    "Sahibganj": "Sahibganj",
    "Saiha": "सैहा",
    "Salem": "सलेम",
    "Samalkha": "Samalkha",
    "Samalkota": "Samalkota",
    "Samastipur": "Samastipur",
    "Samba": "साम्बा",
    "Sambalpur": "संबलपुर",
    "Sambhal": "Sambhal",
    "Sambhar Lake": "संभार झील",
    "Sampla": "उदाहरण",
    "Samrala": "Samrala",
    "Sanand": "Sanand",
    "Sanchore": "Sanchore",
    "Sandila": "संडीला",
    "Sangamner": "संगमनेर",
    "Sangareddi": "Sangareddi",
    "Sanghol": "Sanghol",
    "Sangli": "सांगली",
    "Sangrur": "Sangrur",
    "Sankarankovil": "Sankarankovil",
    "Sant Kabir Nagar": "Sant Kabir Nagar",
    "Sant Ravidas Nagar": "Sant Ravidas Nagar",
    "Santiniketan": "शांति निकेतन",
    "Santrampur": "हलोल",
    "Sanwer": "Sanwer",
    "Saraipali": "Saraipali",
    "Saran": "सुझाव",
    "Sarangarh": "Sarangarh",
    "Sarhali": "सरहली",
    "Sasaram": "Sasaram",
    "Sasthamkotta": "सस्थमकोट्टा",
    "Saswad": "Saswad",
    "Satana": "शैतान",
    "Satara": "सतारा",
    "Sathupalli": "Sathupalli",
    "Satna": "घंटा",
    "Sattenapalli": "सत्तेनापल्ली",
    "Satyamanglam": "Satyamanglam",
    "Sawai madhopur": "Sawai madhopur",
    "Sawantwadi": "सावंतवाडी",
    "Sayan": "सयान",
    "Secunderabad": "सिकंदराबाद",
    "Sehore": "सीहोर",
    "Senapati": "सेनापति",
    "Seoni": "सिवनी",
    "Seraikela-kharsawan": "Seraikela-kharsawan",
    "Serchhip": "सेरछिप",
    "Shahabad": "Shahabad",
    "Shahad": "Shahad",
    "Shahbad": "Shahbad",
    "Shahdol": "Shahdol",
    "Shahjahanpur": "Shahjahanpur",
    "Shahpura": "शाहपुरा",
    "Shajapur": "Shajapur",
    "Shamli": "Shamli",
    "Sheikhpura": "शेखपुरा",
    "Sheohar": "Sheohar",
    "Sheopur": "Sheopur",
    "Shergarh (RJ)": "शेरगढ़ (आरजे)",
    "Shikohabad": "Shikohabad",
    "Shillong": "शिलांग",
    "Shimla": "शिमला",
    "Shimoga": "शिमोगा",
    "Shirdi": "शिरडी",
    "Shirur": "शिरुर",
    "Shivpuri": "Shivpuri",
    "Sholavandan": "Sholavandan",
    "Shorapur": "Shorapur",
    "Shravasti": "Shravasti",
    "Shrigonda": "श्रीगोंदा",
    "Shrirampur": "श्रीरामपुर",
    "Shrivaikuntam": "Shrivaikuntam",
    "Shujalpur": "Shujalpur",
    "Siddapura": "Siddapura",
    "Siddharthnagar": "Siddharthnagar",
    "Siddipet": "Siddipet",
    "Sidhi": "Sidhi",
    "Sikandrabad": "Sikandrabad",
    "Sikar": "सीकर",
    "Silchar": "सिलचर",
    "Siliguri": "सिलीगुड़ी",
    "Sillod": "सिल्लोड",
    "Silvassa": "सिल्वासा",
    "Simdega": "Simdega",
    "Sindhanur": "Sindhanur",
    "Sindhudurg": "सिंधुदुर्ग",
    "Sindri": "सिंदरी",
    "Singrauli": "सिंगरौली",
    "Singtam": "सिंगताम",
    "Sinnar": "सिन्नर",
    "Sirhind-Fategarh": "सरहिंद-Fategarh",
    "Sirkazhi": "Sirkazhi",
    "Sirmaur": "Sirmaur",
    "Sirohi": "सिरोही",
    "Sirsa": "Sirsa",
    "Sirsi": "सिरसी",
    "Sitamarhi": "Sitamarhi",
    "Sitapur": "Sitapur",
    "Sitarganj": "Sitarganj",
    "Sivaganga": "शिवगंगा",
    "Sivakasi": "Sivakasi",
    "Sivasagar": "शिवसागर",
    "Siwan": "सिवान",
    "Sodawas": "Sodawas",
    "Sohna": "सोहना",
    "Sojat": "सोजत",
    "Solan": "Solan",
    "Solapur": "सोलापुर",
    "Sonbhadra": "Sonbhadra",
    "Sonepur": "सोनेपुर",
    "Sonepur(OR)": "सोनेपुर (या)",
    "Sonipat": "Sonipat",
    "Sonitpur": "सोनितपुर",
    "Soron": "पंक्ति",
    "South 24 Parganas": "दक्षिण 24 परगना",
    "South Garo Hills": "दक्षिण गारो हिल्स",
    "South Tripura": "दक्षिण त्रिपुरा",
    "Sri Ganganagar": "Sri Ganganagar",
    "Sri Karanpur": "श्री करणपुर",
    "Sri Madhopur": "श्री माधोपुर",
    "Sri Muktsar Sahib": "श्री मुक्तासर साहिब",
    "Srikakulam": "श्रीकाकुलम",
    "Srikalahasti": "Srikalahasti",
    "Srinagar": "श्रीनगर",
    "Srinagar (UK)": "श्रीनगर (यूके)",
    "Srirangam": "श्रीरंगम",
    "Srirangapatna": "Srirangapatna",
    "Srivilliputhur": "श्रीविल्लीपुतुर",
    "Sukma": "आत्मा",
    "Sullia": "सुलिया",
    "Sultan Bathery": "सुल्तान बाथेरी",
    "Sultanpur": "Sultanpur",
    "Sultanpur Lodhi": "Sultanpur Lodhi",
    "Sulur": "ज़ुल्फ़",
    "Sumerpur": "Sumerpur",
    "Sunderbani": "सुंदरबनी",
    "Sundergarh": "Sundergarh",
    "Supaul": "Supaul",
    "Surajpur": "Surajpur",
    "Surat": "पत्र",
    "Suratgarh": "Suratgarh",
    "Surathkal": "Surathkal",
    "Surendranagar": "सुरेंद्रनगर",
    "Surguja": "सरगुजा",
    "Suri": "मर गया",
    "Suryapet": "Suryapet",
    "Tadepalligudem": "Tadepalligudem",
    "Tadipatri": "Tadipatri",
    "Talasari": "Talasari",
    "Taleigao": "Taleigao",
    "Taliparamba": "Taliparamba",
    "Talwara": "तलवाड़ा",
    "Tamenglong": "तामेंगलांग",
    "Tamluk": "तामलुक",
    "Tandur": "Tandur",
    "Tanuku": "टनुकु",
    "Tapi": "लेकिन",
    "Tarakeswar": "तारकेश्वर",
    "Tarn Taran": "तरण तारण",
    "Tawang": "तवांग",
    "Tehri": "टिहरी",
    "Tekkali": "Tekkali",
    "Tenali": "तेनाली",
    "Tenkasi": "तेनकासी",
    "Tetri Bazar": "टेट्री बाजार",
    "Tezpur": "तेजपुर",
    "Thalassery": "थालास्सेरी",
    "Thalayolaparambu": "Thalayolaparambu",
    "Thamarassery": "Thamarassery",
    "Thane": "Thane",
    "Thanjavur": "तंजावुर",
    "The Nilgiris": "Nilgiris",
    "Theni": "थेनी",
    "Thiruthuraipoondi": "Thiruthuraipoondi",
    "Thiruttani": "Thiruttani",
    "Thiruvalla": "तिरुवल्ला",
    "Thiruvananthapuram": "तिरुवनंतपुरम",
    "Thiruvarur": "थिरुवरुर",
    "Thodupuzha": "Thodupuzha",
    "Thokottu": "Thokottu",
    "Thoothukudi": "Thoothukudi",
    "Thoubal": "थौबल",
    "Thrissur": "त्रिशूर",
    "Thrithallur": "Thrithallur",
    "Thuckalay": "Thuckalay",
    "Tikamgarh": "Tikamgarh",
    "Tilakwadi": "Tilakwadi",
    "Tindivanam": "Tindivanam",
    "Tinsukia": "तिनसुकिया",
    "Tiptur": "Tiptur",
    "Tirap": "तिरप",
    "Tiruchengode": "तिरुचेंगोडे",
    "Tiruchirappalli": "तिरुचिरापल्ली",
    "Tirukoilur": "Tirukoilur",
    "Tirunelveli": "तिरुनेलवेली",
    "Tirupati": "तिरुपति",
    "Tiruppattur": "Tiruppattur",
    "Tiruppur": "तिरुपूर",
    "Tirur": "तिरूर",
    "Tiruvallur": "तिरुवल्लुर",
    "Tiruvannamalai": "तिरुवन्नामलाई",
    "Tonk": "टोंक",
    "Triprayar": "Triprayar",
    "Tripunithura": "त्रिपुनिथुरा",
    "Tuensang": "तुएनसांग",
    "Tumkur": "Tumkur",
    "Tuni": "तुनि",
    "Tura": "कौआ",
    "Udaipur": "Udaipur",
    "Udalguri": "Udalguri",
    "Udham Singh Nagar": "Udham Singh Nagar",
    "Udhampur": "Udhampur",
    "Udumalaipettai": "उदुमलाईपट्टी",
    "Udupi": "उडुपी",
    "Ujjain": "उज्जैन",
    "Ukhrul": "उखरूल",
    "Ulhasnagar": "Ulhasnagar",
    "Uluberia": "उलूबेरिया",
    "Ulundurpet": "Ulundurpet",
    "Umaria": "Umaria",
    "Umbergaon": "Umbergaon",
    "Una": "एक",
    "Unchahar": "Unchahar",
    "Unjha": "उंझा",
    "Unnao": "Unnao",
    "Uppala": "Uppala",
    "Upper Siang": "ऊपरी सियांग",
    "Upper Subansiri": "ऊपरी सुबानसिरी",
    "Uppinangady": "Uppinangady",
    "Urakam": "Urakam",
    "Urmar Tanda": "उमर साइन",
    "Urun Islampur": "उरुण इस्लामपुर",
    "Uthangudi": "यह एक प्रिय है",
    "Uttar Dinajpur": "उत्तर दिनाजपुर",
    "Uttara Kannada": "उत्तरा कन्नड़",
    "Uttarkashi": "उत्तरकाशी",
    "Vadakara": "Vadakara",
    "Vadkhal": "Vadkhal",
    "Vadodara": "वडोदरा",
    "Vaduj": "Vaduj",
    "Vaijnath": "Vaijnath",
    "Vaikom": "वाईकॉम",
    "Vairengte": "Vairengte",
    "Vaishali": "Vaishali",
    "Valliyur": "Valliyur",
    "Valsad": "वलसाड",
    "Vapi": "राज्य-चिह्न",
    "Varkala": "वर्कला",
    "Vasai": "वसई",
    "Vasco Da Gama": "वास्को दा गामा",
    "Vashi": "वाशी",
    "Vatakara": "Vatakara",
    "Vellore": "वेल्लोर",
    "Vengurla": "Vengurla",
    "Veraval": "वेरावल",
    "Verna": "वेरना",
    "Verna Salcete": "वर्ना साल्केटे",
    "Vettichira": "Vettichira",
    "Vidisha": "Vidisha",
    "Vijapur": "विजापुर",
    "Vijayawada": "विजयवाड़ा",
    "Vikarabad": "विकाराबाद",
    "Vikasnagar": "Vikasnagar",
    "Viluppuram": "विलुप्पुरम",
    "Viramgam": "Viramgam",
    "Virar": "बारी करने के लिए",
    "Virudhachalam": "Virudhachalam",
    "Virudhunagar": "विरुधुनगर",
    "Visakhapatnam": "विशाखापत्तनम",
    "Visnagar": "Visnagar",
    "Vita": "जीवन",
    "Vizianagaram": "विजयनगरम",
    "Wadakkanchery": "वडक्कान्चेरी",
    "Wagholi": "Wagholi",
    "Wai": "वाई",
    "Waidhan": "Waidhan",
    "Waluj": "Waluj",
    "Wanaparthy": "Wanaparthy",
    "Wani": "एक",
    "Warangal": "वारंगल",
    "Wardha": "वर्धा",
    "Warud": "Warud",
    "Washim": "Washim",
    "Wayanad": "वायनाड",
    "West Champaran": "West Champaran",
    "West Garo Hills": "वेस्ट गारो हिल्स",
    "West Godavari": "पश्चिम गोदावरी",
    "West Kameng": "पश्चिम कामेंग",
    "West Khasi Hills": "पश्चिम खासी हिल्स",
    "West Siang": "पश्चिम सियांग",
    "West Singhbhum": "West Singhbhum",
    "West Tripura": "पश्चिम त्रिपुरा",
    "Wokha": "केवल",
    "Yadgir": "Yadgir",
    "Yamuna Nagar": "Yamuna Nagar",
    "Yavatmal": "यवतमाल",
    "Yerraguntla": "येरागुंटला",
    "Yuksam": "Yuksam",
    "Zahirabad": "Zahirabad",
    "Zamania": "Zamania",
    "Zira": "क्योंकि",
    "Zirakpur": "जीरकपुर",
    "Zunheboto": "Zunheboto",
    " Comments": "टिप्पणियाँ",
    "View Details":"विवरण देखें",
    "News" : "समाचार",
    "Search for Cars and more" : "कारों और अधिक खोजें",
    'Select City' : "शहर चुनें",
    "Type your city, e.g. Jaipur, New Delhi" : "अपना शहर टाइप करें, उदा। जयपुर, नई दिल्ली",
    "Expected Launch" : "अपेक्षित लॉन्च",
    "Get trusted used cars nearby":"पास में इस्तेमाल की जाने वाली विश्वसनीय कारें ",
    "Search your city here" : "यहां अपने शहर की खोज करें",
    "Enter your city" : "अपना शहर दर्ज करें",
    "By Brand" :"ब्रांड द्वारा",
    "By Budget" :"बजट से",
    "New Car" :"नई कार" ,
    "Used Car" :"उपयोग किया गया मोटर",
    "Advanced Search" :"उन्नत खोज",
    "By Model" :"मॉडल द्वारा",
    "By Budget" :"बजट से",
    "Alert Me When Launched" :"लॉन्च होने पर मुझे चेतावनी दें",
    "Used cars in" : "में प्रयुक्त कारें",
    "I am looking to buy a second hand car in" :"मैं दूसरी हाथ की कार खरीदने की तलाश में हूं",
    "Select City" : "शहर चुनें",
    "Which is your city ?" : "आपका शहर कौन सा है?",
    "Recent": "हाल का",
    "Trending": "रुझान",
    "Overview": "अवलोकन",
    "Price": "मूल्य",
    "Compare": "तुलना",
    "Specs": "ऐनक",
    "Images": "इमेजिस",
    "360 View": "360 देखें",
    "Variants": "वेरिएंट",
    "Videos": "वीडियो",
    "User Reviews": "उपयोगकर्ता समीक्षा",
    "More": "अधिक",
    "Offers": "ऑफर",
    "Select City": "शहर चुनें",
    "Which is your city ?": "आपका शहर कौन सा है?",
    "Recent": "हाल का",
    "Trending": "रुझान",
    "Overview": "अवलोकन",
    "Price": "मूल्य",
    "Compare": "तुलना",
    "Specs": "ऐनक",
    "Images": "इमेजिस",
    "360 View": "360 देखें",
    "Variants": "वेरिएंट",
    "Videos": "वीडियो",
    "User Reviews": "उपयोगकर्ता समीक्षा",
    "More": "अधिक",
    "Offers": "ऑफर",
    "Colours": "रंग की",
    "Mileage": "लाभ",
    "Service Cost": "सेवा लागत",
    "Spare Parts": "स्पेयर पार्ट्स",
    "FAQ": "सामान्य प्रश्न",
    "EMI Calculator": "ईएमआई कैलकुलेटर",
    "Brochures": "ब्रोशर",
    "Dealers": "सौदागर",
    "Loan": "ऋण",
    "Car Insurance": "कार बीमा",
    "Popular hatchback Cars": "लोकप्रिय हैचबैक कारें",
    "Upcoming Hatchback Cars": "आगामी हैचबैक कारें",
    "Latest Hatchback Cars": "नवीनतम हैचबैक कारें",
    "Nano Images": "नैनो छवियाँ",
    "Petrol": "पेट्रोल",
    "CNG": "सीएनजी",
    "Transmission": "हस्तांतरण",
    "Manual/Automatic": "मैन्युअल / स्वचालित",
    "Select Feature Category": "फ़ीचर श्रेणी का चयन करें",
    "Select Brand": "ब्रांड का चयन करें",
    "Select Model": "मॉडल का चयन करें",
    "Search by Road Test": "रोड टेस्ट द्वारा खोजें",
    "Select Your Car": "अपनी कार का चयन करें",
    "Tips for a Good Review": "एक अच्छी समीक्षा के लिए सुझाव",
    "List out the pros and cons of your car": "अपनी कार के पेशेवरों और विपक्ष की सूची बनाएं",
    "How's the after-sales service and what are the costs involved": "बिक्री के बाद सेवा और लागत में क्या शामिल है",
    "Give a suitable title to your review": "अपनी समीक्षा में उपयुक्त शीर्षक दें",
    "Don't use all caps and avoid sharing personal details here": "सभी कैप्स का उपयोग न करें और यहां व्यक्तिगत विवरण साझा करने से बचें",
    "Write a Review": "एक समीक्षा लिखे",
    "Contest Guidelines (T&C)": "प्रतियोगिता दिशानिर्देश (टी एंड सी)",
    "Nissan": "निसान",
    "Nissan GTR": "निसान जीटीआर",
    "Nissan Terrano": "निसान टेरानो",
    "Nissan Micra Active": "निसान माइक्रो सक्रिय",
    "Nissan Micra": "निसान माइक्रोरा",
    "Nissan Sunny": "निसान सनी",
    "Mahindra e2o": "महिंद्रा ई 2o",
    "Mahindra Willys": "महिंद्रा विलीज़",
    "Mahindra Armada": "महिंद्रा आर्मडा",
    "Mahindra Inferno": "महिंद्रा इन्फर्नो",
    "Mahindra Jeep": "महिंद्रा जीप",
    "Mahindra Ingenio": "महिंद्रा इंजेनिओ",
    "Mahindra Voyeger 1997-2002": "महिंद्रा वॉयजर 1997-2002",
    "Mahindra Logan": "महिंद्रा लोगान",
    "Mahindra Rexton": "महिंद्रा रेक्सटन",
    "Mahindra U321 MPV": "महिंद्रा यू 321 एमपीवी",
    "Mahindra Quanto": "महिंद्रा क्वांटो",
    "Mahindra XUV700": "महिंद्रा एक्सयूवी 700",
    "Mahindra Marshal": "महिंद्रा मार्शल",
    "Aston Martin DBX": "एस्टन मार्टिन डीबीएक्स",
    "Datsun": "डैटसन",
    "Datsun GO Plus": "Datsun जाओ प्लस",
    "Datsun GO": "Datsun जाओ",
    "Datsun RediGO": "Datsun RediGO",
    "Honda Civic 2006-2010": "होंडा सिविक 2006-2010",
    "Honda HR-V": "होंडा एचआर-वी",
    "Honda Mobilio": "होंडा Mobilio",
    "Honda City ZX": "होंडा सिटी जेएक्स",
    "Honda Civic 2010-2013": "होंडा सिविक 2010-2013",
    "Mahindra S 201": "महिंद्रा एस 201",
    "Mahindra XUV Aero": "महिंद्रा एक्सयूवी एयरो",
    "Mahindra eKUV100": "महिंद्रा केयूवी 100",
    "Toyota": "टोयोटा",
    "Toyota Yaris": "टोयोटा यारीस",
    "Toyota Etios Cross": "टोयोटा ईटीओएस क्रॉस",
    "Toyota Etios": "टोयोटा Etios",
    "Toyota Innova Crysta": "टोयोटा इनोवा क्रिस्टा",
    "Toyota Corolla Altis": "टोयोटा कोरोला अल्टीस",
    "Toyota Fortuner": "टोयोटा फॉर्च्यूनर",
    "Toyota Land Cruiser": "टोयोटा लैंड क्रूजर",
    "Toyota Land Cruiser Prado": "टोयोटा लैंड क्रूजर प्राडो",
    "Toyota Etios Liva": "टोयोटा ईटीओस लिवा",
    "Toyota Prius": "टोयोटा प्रियस",
    "Volkswagen Jetta 2012-2014": "वोक्सवैगन जेटटा 2012-2014",
    "Volkswagen Jetta": "वोक्सवैगन जेटटा",
    "Volkswagen Phaeton": "वोक्सवैगन फाएटन",
    "Volkswagen 1600": "वोक्सवैगन 1600",
    "Volkswagen Caraville": "वोक्सवैगन कैरविल",
    "Volkswagen Beetle": "वोक्सवैगन बीटल",
    "Volkswagen Polo GTI": "वोक्सवैगन पोलो जीटीआई",
    "Volkswagen Multivan": "वोक्सवैगन मल्टीवन",
    "Volkswagen CrossPolo": "वोक्सवैगन क्रॉसपोलो",
    "Volkswagen Touareg": "वोक्सवैगन टौअरेग",
    "Volkswagen": "वोक्सवैगन",
    "Volkswagen Tiguan": "वोक्सवैगन टिगुआन",
    "Volkswagen Vento": "वोक्सवैगन वेंटो",
    "Volkswagen Passat": "वोक्सवैगन पासैट",
    "Volkswagen Polo": "वोक्सवैगन पोलो",
    "Volkswagen Ameo": "वोक्सवैगन अमीओ",
    "Volkswagen GTI": "वोक्सवैगन जीटीआई",
    "Ashok Leyland": "अशोक लेलैंड",
    "Ashok Leyland Stile": "अशोक लेलैंड स्टाइल",
    "Maruti WagonR Electric": "मारुति वैगनआर इलेक्ट्रिक",
    "Maruti Baleno": "मारुति बालेनो",
    "Maruti Grand Vitara": "मारुति ग्रैंड विटारा",
    "Maruti Wagon R": "मारुति वैगन आर",
    "Aston Martin": "एस्टन मार्टिन",
    "Aston Martin Rapide": "एस्टन मार्टिन रैपिड",
    "Aston Martin DB11": "एस्टन मार्टिन डीबी 11",
    "Aston Martin Vanquish": "एस्टन मार्टिन वैंकुश",
    "Aston Martin Vantage": "एस्टन मार्टिन लाभ",
    "Tata Movus": "टाटा मूवस",
    "Tata Indica Vista": "टाटा इंडिका विस्टा",
    "Tata Estate": "टाटा एस्टेट",
    "Tata Venture": "टाटा वेंचर",
    "Tata Winger": "टाटा विंगर",
    "Tata Sierra": "टाटा सिएरा",
    "Tata Indica": "टाटा इंडिका",
    "Tata Indigo CS": "टाटा इंडिगो सीएस",
    "Tata Manza": "टाटा मांजा",
    "Tata H5X": "टाटा एच 5 एक्स",
    "Tata Sumo Victa": "टाटा सुमो विक्टा",
    "Tata Aria": "टाटा एरिया",
    "Tata New Safari": "टाटा न्यू सफारी",
    "Tata Indica V2": "टाटा इंडिका वी 2",
    "Tata Xenon XT": "टाटा जेनॉन एक्सटी",
    "Tata Spacio": "टाटा स्पासिओ",
    "Tata Indigo XL": "टाटा इंडिगो एक्सएल",
    "Tata Indigo": "टाटा इंडिगो",
    "BMW 3 Series": "बीएमडब्ल्यू 3 श्रृंखला",
    "BMW 4 Series": "बीएमडब्ल्यू 4 श्रृंखला",
    "BMW i3": "बीएमडब्ल्यू i3",
    "BMW X2": "बीएमडब्ल्यू एक्स 2",
    "BMW X4": "बीएमडब्ल्यू एक्स 4",
    "BMW X5": "बीएमडब्ल्यू एक्स 5",
    "BMW 8 Series": "बीएमडब्ल्यू 8 श्रृंखला",
    "BMW i8": "बीएमडब्ल्यू i8",
    "BMW X7": "बीएमडब्ल्यू एक्स 7",
    "Audi": "ऑडी",
    "Audi Q3": "ऑडी क्यू 3",
    "Audi S5": "ऑडी एस 5",
    "Audi Q5": "ऑडी क्यू 5",
    "Audi Q7": "ऑडी क्यू 7",
    "Audi R8": "ऑडी आर 8",
    "Audi RS6": "ऑडी आरएस 6",
    "Audi A3 cabriolet": "ऑडी ए 3 कैब्रिलेट",
    "Audi A3": "ऑडी ए 3",
    "Audi A4": "ऑडी ए 4",
    "Audi RS5": "ऑडी आरएस 5",
    "Audi A5": "ऑडी ए 5",
    "Audi A6": "ऑडी ए 6",
    "Audi RS7": "ऑडी आरएस 7",
    "Audi A8": "ऑडी ए 8",
    "Audi TT": "ऑडी टीटी",
    "Austin A40": "ऑस्टिन ए 40",
    "Austin": "ऑस्टिन",
    "Bajaj": "बजाज",
    "Bajaj RE60": "बजाज आरई 60",
    "Bentley": "बेंटले",
    "Bentley Bentayga": "बेंटले बेंटयागा",
    "Bentley Mulsanne": "बेंटले मल्सैन",
    "Bentley Continental": "बेंटले कॉन्टिनेंटल",
    "Bentley Flying Spur": "बेंटले फ्लाइंग स्पूर",
    "BMW": "बीएमडब्ल्यू",
    "BMW 7 Series": "बीएमडब्ल्यू 7 श्रृंखला",
    "BMW M Series": "बीएमडब्लू एम सीरीज",
    "BMW M2": "बीएमडब्ल्यू एम 2",
    "BMW X1": "बीएमडब्ल्यू एक्स 1",
    "BMW X3": "बीएमडब्ल्यू एक्स 3",
    "BMW 5 Series": "बीएमडब्ल्यू 5 श्रृंखला",
    "BMW 6 Series": "बीएमडब्ल्यू 6 श्रृंखला",
    "BMW X6": "बीएमडब्ल्यू एक्स 6",
    "Toyota Innova": "टोयोटा इनोवा",
    "Toyota Estima Emina": "टोयोटा एस्टिमा एमिना",
    "Toyota MR2": "टोयोटा एमआर 2",
    "Toyota Crown": "टोयोटा क्राउन",
    "Toyota Tercel": "टोयोटा टेर्सल",
    "Toyota Alphard": "टोयोटा अल्फार्ड",
    "Toyota prado": "टोयोटा प्राडो",
    "Toyota Sera": "टोयोटा सेरा",
    "Toyota Starlet": "टोयोटा स्टार्लेट",
    "Toyota Commuter": "टोयोटा कम्यूटर",
    "Toyota Qualis": "टोयोटा Qualis",
    "Toyota Corolla": "टोयोटा कोरोला",
    "Toyota Cynos": "टोयोटा साइनोस",
    "Toyota Previa": "टोयोटा प्रीविया",
    "Toyota Premio": "टोयोटा Premio",
    "Toyota Majesta": "टोयोटा मेजेस्टा",
    "Toyota Corona": "टोयोटा कोरोना",
    "Bugatti": "बुगाटी",
    "Bugatti Chiron": "बुगाटी चिरॉन",
    "Bugatti Divo": "बुगाटी डिवो",
    "Bugatti Veyron": "बुगाटी वेरॉन",
    "Honda Civic 2006-2010": "होंडा सिविक 2006-2010",
    "Honda HR-V": "होंडा एचआर-वी",
    "Honda Mobilio": "होंडा Mobilio",
    "Honda City ZX": "होंडा सिटी जेएक्स",
    "Honda Civic 2010-2013": "होंडा सिविक 2010-2013",
    "Mahindra S 201": "महिंद्रा एस 201",
    "Mahindra TUV 300": "महिंद्रा टीयूवी 300",
    "Mahindra XUV Aero": "महिंद्रा एक्सयूवी एयरो",
    "Mahindra eKUV100": "महिंद्रा ईकेयूवी 100",
    "Cadillac": "कैडिलैक",
    "Cadillac CTS": "कैडिलैक सीटीएस",
    "Cadillac STS": "एसटीएस कैडिलैक",
    "Cadillac Escalade": "कैडिलैक एस्कैलेड",
    "Honda Civic": "होंडा सिविक",
    "Honda Brio": "होंडा ब्रियो",
    "Honda VEZEL": "होंडा वेज़ेल",
    "Caterham": "Caterham",
    "Caterham 7": "कैटरहम 7",
    "Chevrolet": "शेवरलेट",
    "Chevrolet Aveo": "शेवरलेट Aveo",
    "Chevrolet Aveo U-VA": "शेवरलेट Aveo यू-वीए",
    "Chevrolet Beat": "शेवरलेट बीट",
    "Chevrolet Optra": "शेवरलेट ऑप्ट्रा",
    "Chevrolet Tavera": "शेवरलेट तावेरा",
    "Chevrolet Trailblazer": "शेवरलेट ट्रिलब्लैज़र",
    "Chevrolet Silverado": "शेवरलेट सिल्वरैडो",
    "Chevrolet Tavera Neo": "शेवरलेट तावेरा नियो",
    "Chevrolet Cruze": "शेवरलेट क्रूज",
    "Chevrolet Enjoy": "शेवरलेट का आनंद लें",
    "Chevrolet Corvette": "शेवरलेट कार्वेट",
    "Chevrolet Optra Magnum": "शेवरलेट ऑप्ट्रा मैग्नम",
    "Chevrolet Sail": "शेवरलेट सेल",
    "Chevrolet Sail Hatchback": "शेवरलेट सेल हैचबैक",
    "Chevrolet Captiva": "शेवरलेट कैप्टिव",
    "Chevrolet Forester": "शेवरलेट फॉरेस्टर",
    "Chevrolet Spark": "शेवरलेट स्पार्क",
    "Chevrolet OptraSRV": "शेवरलेट ऑप्ट्राएसआरवी",
    "Chrysler": "क्रिसलर",
    "Chrysler 300": "क्रिसलर 300",
    "Chrysler Avenger": "क्रिसलर एवेंजर",
    "Hyundai Kona": "हुंडई कोना",
    "Hyundai Carlino": "हुंडई कार्लिनो",
    "Hyundai Santa Fe": "हुंडई सांता फे",
    "Hyundai Ioniq": "हुंडई Ioniq",
    "Hyundai Elantra": "हुंडई एलेंट्रा",
    "Hyundai Sonata": "हुंडई सोनाटा",
    "Hyundai Grand i10 2019": "हुंडई ग्रांड आई 10 201 9",
    "Citroen": "Citroen",
    "Citroen C5 Aircross": "साइट्रॉन सी 5 एयरक्रॉस",
    "Conquest": "विजय",
    "Conquest Evade": "विजय Evade",
    "Daewoo": "देवू",
    "Daewoo Cielo": "देवू सिएलो",
    "Daewoo Nexia": "देवू नेक्सिया",
    "Daewoo Matiz": "देवू मटिज़",
    "DC": "डीसी",
    "DC Avanti": "डीसी अवंती",
    "Maruti Zen Estilo": "मारुति जेन एस्टिलो",
    "Maruti A-Star": "मारुति ए-स्टार",
    "Maruti Kizashi": "मारुति किज़ाशी",
    "Maruti Ciaz 2018": "मारुति सीआज़ 2018",
    "Maruti Esteem": "मारुति एस्टीम",
    "Maruti SX4": "मारुति एसएक्स 4",
    "Maruti 800": "मारुति 800",
    "Maruti Ritz": "मारुति रिट्ज",
    "Maruti Ciaz S": "मारुति सिएज़ एस",
    "Maruti Versa": "मारुति वर्सा",
    "Maruti Zen": "मारुति जेन",
    "Maruti 1000": "मारुति 1000",
    "Maruti Estilo": "मारुति एस्टिलो",
    "Maruti Ertiga 2018": "मारुति एर्टिगा 2018",
    "Maruti Alto": "मारुति अल्टो",
    "Maruti Wagon R Stingray": "मारुति वैगन आर स्टिंग्रे",
    "Dodge": "चकमा",
    "Dodge Nitro": "डॉज नाइट्रो",
    "Ferrari": "फेरारी",
    "Ferrari 488 GTB": "फेरारी 488 जीटीबी",
    "Ferrari GTC4Lusso": "फेरारी जीटीसी 4 लुससो",
    "Ferrari Portofino": "फेरारी पोर्टफिनो",
    "Ferrari 812 SuperFast": "फेरारी 812 सुपरफ़ास्ट",
    "Fiat": "व्यवस्थापत्र",
    "Fiat Linea Classic": "फिएट लाइनिया क्लासिक",
    "Fiat Avventura": "फिएट अव्वेंटुरा",
    "Fiat Avventura Urban Cross": "फिएट अव्वेंटुरा शहरी क्रॉस",
    "Fiat 500": "फिएट 500",
    "Fiat Punto EVO": "फिएट पंटो ईवीओ",
    "Fiat Abarth Avventura": "फिएट अर्थ अवेवेंटुरा",
    "Fiat Punto Abarth": "फिएट पंटो अर्थ",
    "Fiat Linea": "फिएट लाइनिया",
    "Fiat Punto": "फिएट पंटो",
    "Force": "बल",
    "Force Gurkha": "गुरखा फोर्स",
    "Hindustan Motors": "हिंदुस्तान मोटर्स",
    "Hindustan Motors Contessa": "हिंदुस्तान मोटर्स कोंटेसा",
    "Ambassador": "दूत",
    "Hyundai Kona": "हुंडई कोना",
    "Hyundai Carlino": "हुंडई कार्लिनो",
    "Hyundai Santa Fe": "हुंडई सांता फे",
    "Hyundai Ioniq": "हुंडई Ioniq",
    "Hyundai Elantra": "हुंडई एलेंट्रा",
    "Hyundai Sonata": "हुंडई सोनाटा",
    "Hyundai Grand i10 2019": "हुंडई ग्रांड आई 10 201 9",
    "ICML": "आईसीएमएल",
    "ICML Extreme": "आईसीएमएल चरम",
    "Maruti Zen Estilo": "मारुति जेन एस्टिलो",
    "Maruti A-Star": "मारुति ए-स्टार",
    "Maruti Kizashi": "मारुति किज़ाशी",
    "Maruti Ciaz 2018": "मारुति सीआज़ 2018",
    "Maruti Esteem": "मारुति एस्टीम",
    "Maruti SX4": "मारुति एसएक्स 4",
    "Maruti Grand Vitara": "मारुति ग्रैंड विटारा",
    "Maruti 800": "मारुति 800",
    "Maruti Ritz": "मारुति रिट्ज",
    "Maruti Ciaz S": "मारुति सिएज़ एस",
    "Maruti Versa": "मारुति वर्सा",
    "Maruti Zen": "मारुति जेन",
    "Maruti 1000": "मारुति 1000",
    "Maruti Estilo": "मारुति एस्टिलो",
    "Maruti Ertiga 2018": "मारुति एर्टिगा 2018",
    "Maruti Alto": "मारुति अल्टो",
    "Maruti Wagon R Stingray": "मारुति वैगन आर स्टिंग्रे",
    "Infiniti": "इनफिनिटी",
    "Infiniti FX": "इंफिनिटी एफएक्स",
    "Maruti WagonR Electric": "मारुति वैगनआर इलेक्ट्रिक",
    "Maruti Baleno": "मारुति बालेनो",
    "Maruti Wagon R": "मारुति वैगन आर",
    "Isuzu": "इसुजु",
    "Isuzu D-Max V-Cross": "इसुजू डी-मैक्स वी-क्रॉस",
    "Isuzu MU-X": "Isuzu एमयू-एक्स",
    "Hyundai Getz": "हुंडई गेटज़",
    "Hyundai Sonata Transform": "हुंडई सोनाटा ट्रांसफॉर्म",
    "Hyundai Small Car": "हुंडई छोटी कार",
    "Hyundai Accent": "हुंडई एक्सेंट",
    "Hyundai Avante": "हुंडई अवंत",
    "Hyundai i10": "हुंडई i10",
    "Hyundai Sonata": "हुंडई सोनाटा",
    "Hyundai Terracan": "हुंडई टेराकन",
    "Hyundai Santa Fe": "हुंडई सांता फे",
    "Hyundai Santro Xing": "हुंडई सैंट्रो ज़िंग",
    "Hyundai Sonata Embera": "हुंडई सोनाटा एम्बेरा",
    "Volkswagen Jetta": "वोक्सवैगन जेटटा",
    "Volkswagen T-Cross": "वोक्सवैगन टी-क्रॉस",
    "Volkswagen Virtus": "वोक्सवैगन वर्तुस",
    "Jaguar": "एक प्रकार का जानवर",
    "Jaguar XJ": "जगुआर एक्सजे",
    "Jaguar F-Pace": "जगुआर एफ-पेस",
    "Jaguar XE": "जगुआर एक्सई",
    "Jaguar F Type": "जगुआर एफ प्रकार",
    "Jaguar XF": "जगुआर एक्सएफ",
    "Mahindra e2o": "महिंद्रा ई 2o",
    "Mahindra Willys": "महिंद्रा विलीज़",
    "Mahindra Armada": "महिंद्रा आर्मडा",
    "Mahindra Inferno": "महिंद्रा इन्फर्नो",
    "Mahindra Jeep": "महिंद्रा जीप",
    "Mahindra Ingenio": "महिंद्रा इंजेनिओ",
    "Mahindra Voyeger 1997-2002": "महिंद्रा वॉयजर 1997-2002",
    "Mahindra Logan": "महिंद्रा लोगान",
    "Mahindra Rexton": "महिंद्रा रेक्सटन",
    "Mahindra U321 MPV": "महिंद्रा यू 321 एमपीवी",
    "Mahindra Quanto": "महिंद्रा क्वांटो",
    "Mahindra XUV700": "महिंद्रा एक्सयूवी 700",
    "Mahindra Marshal": "महिंद्रा मार्शल",
    "Aston Martin DBX": "एस्टन मार्टिन डीबीएक्स",
    "Jeep": "जीप",
    "Jeep Wrangler": "जीप रैंगलर",
    "Jeep Grand Cherokee": "जीप ग्रैंड चेरोकी",
    "Jeep Compass": "जीप कम्पास",
    "Honda Civic 2006-2010": "होंडा सिविक 2006-2010",
    "Honda HR-V": "होंडा एचआर-वी",
    "Honda Mobilio": "होंडा Mobilio",
    "Honda City ZX": "होंडा सिटी जेएक्स",
    "Honda Civic 2010-2013": "होंडा सिविक 2010-2013",
    "Mahindra S 201": "महिंद्रा एस 201",
    "Mahindra TUV 300": "महिंद्रा टीयूवी 300",
    "Mahindra XUV Aero": "महिंद्रा एक्सयूवी एयरो",
    "Mahindra eKUV100": "महिंद्रा ईकेयूवी 100",
    "Kia": "किआ",
    "Kia Stonic": "किआ स्टोनिक",
    "Kia Picanto": "किआ Picanto",
    "Kia SP Concept": "किआ एसपी अवधारणा",
    "Kia Soul": "किआ आत्मा",
    "Kia Rio": "किआ रियो",
    "Kia Sportage": "किआ स्पोर्टेज",
    "Kia Ceed": "किआ सईद",
    "Kia Stinger": "किआ स्टिंगर",
    "Koenigsegg": "Koenigsegg",
    "Lamborghini": "लेम्बोर्गिनी",
    "Lamborghini Urus": "लेम्बोर्गिनी यूरस",
    "Lamborghini Huracan": "लेम्बोर्गिनी हुराकान",
    "Lamborghini Aventador": "लेम्बोर्गिनी अवेन्टडोर",
    "Land Rover": "लैंड रोवर",
    "Land Rover Range Rover Velar": "लैंड रोवर रेंज रोवर वेलर",
    "Land Rover Discovery": "लैंड रोवर डिस्कवरी",
    "Land Rover Discovery Sport": "लैंड रोवर डिस्कवरी स्पोर्ट",
    "Land Rover Range Rover Evoque": "लैंड रोवर रेंज रोवर इवोक",
    "Land Rover Range Rover": "लैंड रोवर रेंज रोवर",
    "Land Rover Range Rover Sport": "लैंड रोवर रेंज रोवर स्पोर्ट",
    "Renault Scala": "रेनॉल्ट स्कैला",
    "Renault Fluence": "रेनॉल्ट फ्लुएंस",
    "Renault Pulse": "रेनॉल्ट पल्स",
    "Renault Koleos": "रेनॉल्ट कोयोलोस",
    "Tata 45X": "टाटा 45 एक्स",
    "Tata H7X": "टाटा एच 7 एक्स",
    "Tata Tiago EV": "टाटा टियागो ईवी",
    "Tata EVision": "टाटा ईविजन",
    "Tata Harrier": "टाटा हैरियर",
    "Tata Tigor EV": "टाटा टाइगर ईवी",
    "Lexus": "लेक्सस",
    "Lexus RX": "लेक्सस आरएक्स",
    "Lexus LS": "लेक्सस एलएस",
    "Lexus NX": "लेक्सस एनएक्स",
    "Lexus LX": "लेक्सस एलएक्स",
    "Lexus ES": "लेक्सस ईएस",
    "Mahindra Renault": "महिंद्रा रेनॉल्ट",
    "Mahindra Renault Logan": "महिंद्रा रेनॉल्ट लोगान",
    "Mahindra Ssangyong": "महिंद्रा एससांगोंग",
    "Mahindra Ssangyong Rexton": "महिंद्रा एससांगोंग रेक्सटन",
    "Maserati": "Maserati",
    "Maserati Quattroporte": "मासेराटी क्वाट्रोपोर्ट",
    "Maserati Ghibli": "मासेराटी घिब्ली",
    "Maserati Levante": "मासेराटी लेवेंटे",
    "Maserati Gran Cabrio": "मासेराटी ग्रैन कैब्रिओ",
    "Maserati Gran Turismo": "मासेराटी ग्रैन टुरिस्मो",
    "Maybach": "Maybach",
    "Maybach 62 S": "मेबाच 62 एस",
    "Maybach 57 S": "मेबाच 57 एस",
    "Hyundai Kona": "हुंडई कोना",
    "Hyundai Carlino": "हुंडई कार्लिनो",
    "Hyundai Ioniq": "हुंडई Ioniq",
    "Hyundai Elantra": "हुंडई एलेंट्रा",
    "Mazda": "माजदा",
    "Mazda RX 8": "माज़दा आरएक्स 8",
    "Mazda Miata": "माज़दा मियाटा",
    "Mercedes-Benz": "मर्सिडीज बेंज",
    "Mercedes-Benz New C-Class": "मर्सिडीज-बेंज न्यू सी-क्लास",
    "Mercedes-Benz B Class": "मर्सिडीज-बेंज बी कक्षा",
    "Mercedes-Benz GLA": "मर्सिडीज-बेंज जीएलए",
    "Mercedes-Benz CLS-Class": "मर्सिडीज-बेंज सीएलएस-कक्षा",
    "Mercedes-Benz SLC": "मर्सिडीज-बेंज एसएलसी",
    "Mercedes-Benz A Class": "मर्सिडीज-बेंज ए क्लास",
    "Mercedes-Benz GLS": "मर्सिडीज-बेंज जीएलएस",
    "Mercedes-Benz S-Class": "मर्सिडीज-बेंज एस-क्लास",
    "Mercedes-Benz E-Class": "मर्सिडीज-बेंज ई-क्लास",
    "Mercedes-Benz GLA Class": "मर्सिडीज-बेंज जीएलए कक्षा",
    "Mercedes-Benz CLA": "मर्सिडीज-बेंज सीएलए",
    "Mercedes-Benz G Class": "मर्सिडीज-बेंज जी कक्षा",
    "Mercedes-Benz S-Class Cabriolet": "मर्सिडीज-बेंज एस-क्लास कैब्रियलेट",
    "Mercedes-Benz AMG GT": "मर्सिडीज-बेंज एएमजी जीटी",
    "Mercedes-Benz GLC Class": "मर्सिडीज-बेंज जीएलसी कक्षा",
    "Mercedes-Benz GLE Class": "मर्सिडीज-बेंज जीएलई कक्षा",
    "Bajaj RE60": "बजाज आरई 60",
    "MG": "एमजी",
    "MG ERX5": "एमजी ईआरएक्स 5",
    "MG GS": "एमजी जीएस",
    "MG Baojun 530": "एमजी बाओजुन 530",
    "MG RX5": "एमजी आरएक्स 5",
    "Mini": "छोटा",
    "Mini 3 DOOR": "मिनी 3 दरवाजा",
    "Mini 5 DOOR": "मिनी 5 दरवाजा",
    "Mini Cooper Convertible": "मिनी कूपर परिवर्तनीय",
    "Mini Cooper Clubman": "मिनी कूपर क्लबमैन",
    "Mini Cooper Countryman": "मिनी कूपर कंट्रीमैन",
    "Mitsubishi": "मित्सुबिशी",
    "Mitsubishi Pajero": "मित्सुबिशी पजेरो",
    "Mitsubishi Outlander": "मित्सुबिशी आउटलैंडर",
    "Morris": "मॉरिस",
    "Morris Minor Side Valve": "मॉरिस माइनर साइड वाल्व",
    "Opel": "ओपल",
    "Opel Vectra": "ओपल वेक्टर",
    "Opel Astra": "ओपल एस्ट्रा",
    "OpelCorsa": "OpelCorsa",
    "Honda Civic": "होंडा सिविक",
    "Honda Brio": "होंडा ब्रियो",
    "Honda VEZEL": "होंडा वेज़ेल",
    "Peugeot": "प्यूज़ो",
    "Peugeot 309": "प्यूजोट 30 9",
    "Porsche": "पोर्श",
    "Porsche Macan": "पोर्श मैकन",
    "Porsche Panamera": "पोर्श पैनामेरा",
    "Porsche 911": "पोर्श 911",
    "Porsche Cayenne": "पोर्श केयेन",
    "Porsche 718": "पोर्श 718",
    "Premier": "प्रधान",
    "Premier Rio": "प्रीमियर रियो",
    "Reva": "रेवा",
    "Reva i": "रीवा i",
    "Maruti WagonR Electric": "मारुति वैगनआर इलेक्ट्रिक",
    "Maruti Baleno": "मारुति बालेनो",
    "Maruti Grand Vitara": "मारुति ग्रैंड विटारा",
    "Maruti Wagon R": "मारुति वैगन आर",
    "Rolls-Royce": "रोल्स रॉयस",
    "Rolls-Royce Dawn": "रोल्स-रॉयस डॉन",
    "Rolls-Royce Cullinan": "रोल्स-रॉयस कुलिनन",
    "Rolls-Royce Wraith": "रोल्स-रॉयस वॉरथ",
    "Rolls-Royce Ghost": "रोल्स-रॉयस घोस्ट",
    "Rolls-Royce Phantom": "रोल्स-रॉयस प्रेत",
    "Mahindra e2o": "महिंद्रा ई 2o",
    "Mahindra Willys": "महिंद्रा विलीज़",
    "Mahindra Armada": "महिंद्रा आर्मडा",
    "Mahindra Inferno": "महिंद्रा इन्फर्नो",
    "Mahindra Jeep": "महिंद्रा जीप",
    "Mahindra Ingenio": "महिंद्रा इंजेनिओ",
    "Mahindra Voyeger 1997-2002": "महिंद्रा वॉयजर 1997-2002",
    "Mahindra Logan": "महिंद्रा लोगान",
    "Mahindra Rexton": "महिंद्रा रेक्सटन",
    "Mahindra U321 MPV": "महिंद्रा यू 321 एमपीवी",
    "Mahindra Quanto": "महिंद्रा क्वांटो",
    "Mahindra XUV700": "महिंद्रा एक्सयूवी 700",
    "Mahindra Marshal": "महिंद्रा मार्शल",
    "Aston Martin DBX": "एस्टन मार्टिन डीबीएक्स",
    "San Motors": "सैन मोटर्स",
    "San Motors Storm": "सैन मोटर्स तूफान",
    "Maruti WagonR Electric": "मारुति वैगनआर इलेक्ट्रिक",
    "Maruti Baleno": "मारुति बालेनो",
    "Maruti Grand Vitara": "मारुति ग्रैंड विटारा",
    "Maruti Wagon R": "मारुति वैगन आर",
    "Sipani": "Sipani",
    "Sipani Montego": "सिपानी मोंटेगो",
    "Skoda": "स्कोडा",
    "Skoda Octavia": "स्कोडा ऑक्टाविया",
    "Skoda Superb": "स्कोडा शानदार",
    "Skoda Rapid": "स्कोडा रैपिड",
    "Skoda Kodiaq": "स्कोडा कोडियाक",
    "Tata Movus": "टाटा मूवस",
    "Tata Indica Vista": "टाटा इंडिका विस्टा",
    "Tata Estate": "टाटा एस्टेट",
    "Tata Venture": "टाटा वेंचर",
    "Tata Winger": "टाटा विंगर",
    "Tata Sierra": "टाटा सिएरा",
    "Tata Indica": "टाटा इंडिका",
    "Tata Indigo CS": "टाटा इंडिगो सीएस",
    "Tata Manza": "टाटा मांजा",
    "Tata H5X": "टाटा एच 5 एक्स",
    "Tata Sumo Victa": "टाटा सुमो विक्टा",
    "Tata Aria": "टाटा एरिया",
    "Tata New Safari": "टाटा न्यू सफारी",
    "Tata Indica V2": "टाटा इंडिका वी 2",
    "Tata Xenon XT": "टाटा जेनॉन एक्सटी",
    "Tata Spacio": "टाटा स्पासिओ",
    "Tata Indigo XL": "टाटा इंडिगो एक्सएल",
    "Tata Indigo": "टाटा इंडिगो",
    "BMW 3 Series": "बीएमडब्ल्यू 3 श्रृंखला",
    "BMW 4 Series": "बीएमडब्ल्यू 4 श्रृंखला",
    "BMW i3": "बीएमडब्ल्यू i3",
    "BMW X2": "बीएमडब्ल्यू एक्स 2",
    "BMW X4": "बीएमडब्ल्यू एक्स 4",
    "BMW X5": "बीएमडब्ल्यू एक्स 5",
    "BMW 8 Series": "बीएमडब्ल्यू 8 श्रृंखला",
    "BMW i8": "बीएमडब्ल्यू i8",
    "BMW X7": "बीएमडब्ल्यू एक्स 7",
    "Smart": "होशियार",
    "Smart Fortwo": "स्मार्ट फोर्टवो",
    "Studebaker": "Studebaker",
    "Studebaker Champion": "स्टूडबेकर चैंपियन",
    "Subaru": "सुबारू",
    "Subaru Impreza": "सुबारू इंप्रेजा",
    "Tesla": "टेस्ला",
    "Tesla Model 3": "टेस्ला मॉडल 3",
    "Tesla Model S": "टेस्ला मॉडल एस",
    "Tesla Model X": "टेस्ला मॉडल एक्स",
    "Tesla Model Y": "टेस्ला मॉडल वाई",
    "Volvo": "वोल्वो",
    "Volvo V40": "वोल्वो वी 40",
    "Volvo S60 Cross Country": "वोल्वो एस 60 क्रॉस कंट्री",
    "Volvo S90": "वोल्वो एस 0 9",
    "Volvo V40 Cross Country": "वोल्वो वी 40 क्रॉस कंट्री",
    "Volvo XC 90": "वोल्वो एक्ससी 9 0",
    "Volvo V90 Cross Country": "वोल्वो वी 9 0 क्रॉस कंट्री",
    "Volvo S60": "वोल्वो एस 60",
    "Volvo XC60": "वोल्वो एक्ससी 60",
    "Volvo XC40": "वोल्वो एक्ससी 40",
    "View All" : "सभीें",
    "View All News" : "सभी समाचार देखें",
    "Get On Road Price": "सड़क मूल्य पर जाओ",
    "Ex-showroom Price New Delhi":"एक्स-शोरूम प्राइस नई दिल्ली",
    "Maruti": "मारुति",
    "Maruti Celerio": "मारुति सिलेरियो",
    "Maruti Ertiga": "मारुति एर्टिगा",
    "Maruti Gypsy": "मारुति जिप्सी",
    "Maruti Vitara Brezza": "मारुति विटारा ब्रेज़ा",
    "Maruti Alto K10": "मारुति अल्टो के 10",
    "Maruti Celerio X": "मारुति सेलेरियो एक्स",
    "Maruti Eeco": "मारुति ईको",
    "Maruti Ignis": "मारुति इग्निस",
    "Maruti Wagon R": "मारुति वैगन आर",
    "Maruti Baleno": "मारुति बालेनो",
    "Maruti SX4 S Cross": "मारुति एसएक्स 4 एस क्रॉस",
    "Maruti Swift Dzire": "मारुति स्विफ्ट डिज़ायर",
    "Maruti Baleno RS": "मारुति बालेनो आरएस",
    "Maruti Alto 800": "मारुति अल्टो 800",
    "Maruti Swift": "मारुति स्विफ्ट",
    "Maruti Omni": "मारुति ओमनी",
    "Maruti Ciaz": "मारुति सियाज",
    "Bentley Azure": "बेंटले अज़ूर",
    "Bentley Arnage": "बेंटले अर्नेज",
    "Bentley Brookland": "बेंटले ब्रुकलैंड",
    "Honda Civic": "होंडा सिविक",
    "Honda Brio": "होंडा ब्रियो",
    "Honda VEZEL": "होंडा वेज़ेल",
    "Hyundai": "हुंडई",
    "Hyundai Grand i10": "हुंडई ग्रैंड i10",
    "Hyundai EON": "हुंडई इऑन",
    "Hyundai Creta": "हुंडई Creta",
    "Hyundai i20": "हुंडई आई 20",
    "Hyundai Tucson": "हुंडई टक्सन",
    "Hyundai Xcent": "हुंडई एक्सेंट",
    "Hyundai Elantra": "हुंडई एलेंट्रा",
    "Hyundai Santro": "हुंडई सैंट्रो",
    "Hyundai Verna": "हुंडई वेरना",
    "Hyundai i20 Active": "हुंडई i20 सक्रिय",
    "Toyota Innova": "टोयोटा इनोवा",
    "Toyota Estima Emina": "टोयोटा एस्टिमा एमिना",
    "Toyota MR2": "टोयोटा एमआर 2",
    "Toyota Crown": "टोयोटा क्राउन",
    "Toyota Tercel": "टोयोटा टेर्सल",
    "Toyota Alphard": "टोयोटा अल्फार्ड",
    "Toyota prado": "टोयोटा प्राडो",
    "Toyota Sera": "टोयोटा सेरा",
    "Toyota Starlet": "टोयोटा स्टार्लेट",
    "Toyota Commuter": "टोयोटा कम्यूटर",
    "Toyota Qualis": "टोयोटा Qualis",
    "Toyota Corolla": "टोयोटा करोला",
    "Toyota Cynos": "टोयोटा साइनोस",
    "Toyota Previa": "टोयोटा प्रीविया",
    "Toyota Premio": "टोयोटा Premio",
    "Toyota Majesta": "टोयोटा मेजेस्टा",
    "Toyota Corona": "टोयोटा कोरोना",
    "Honda": "होंडा",
    "Honda Accord": "होंडा एकॉर्ड",
    "Honda BR-V": "होंडा बीआर-वी",
    "Honda Jazz": "होंडा जाज",
    "Honda CR-V": "होंडा सीआर-वी",
    "Honda Amaze": "होंडा अमेज",
    "Honda City": "होंडा सिटी",
    "Honda WR-V": "होंडा डब्लूआर-वी",
    "Nissan Jonga": "निसान जोंगा",
    "Nissan Urvan": "निसान Urvan",
    "Nissan Teana": "निसान टीना",
    "Nissan Gloria": "निसान ग्लोरिया",
    "Nissan X-Trail": "निसान एक्स-ट्रेल",
    "Nissan 370Z": "निसान 370Z",
    "Nissan Primera": "निसान Primera",
    "Nissan Evalia": "निसान इवलिया",
    "Nissan Sunny 2011-2013": "निसान सनी 2011-2013",
    "Nissan 350Z": "निसान 350Z",
    "Toyota Rush": "टोयोटा रश",
    "Toyota Camry": "टोयोटा कैमरी",
    "Toyota C-HR": "टोयोटा सी-एचआर",
    "Tata": "टाटा",
    "Tata Zest": "टाटा ज़ेस्ट",
    "Tata Tiago": "टाटा टियागो",
    "Tata Sumo": "टाटा सुमो",
    "Tata Nexon": "टाटा नेक्सन",
    "Tata Tigor": "टाटा टॉगर",
    "Tata Hexa": "टाटा हेक्सा",
    "Tata Nano": "टाटा नैनो",
    "Tata Safari Storme": "टाटा सफारी स्टोर्म",
    "Tata Bolt": "टाटा बोल्ट",
    "Tata Tiago NRG": "टाटा टियागो एनआरजी",
    "Mahindra": "महिंद्रा",
    "Mahindra NuvoSport": "महिंद्रा नुवोस्पोर्ट",
    "Mahindra Supro": "महिंद्रा सुप्रो",
    "Mahindra Thar": "महिंद्रा थार",
    "Mahindra Scorpio": "महिंद्रा वृश्चिक",
    "Mahindra TUV 300": "महिंद्रा टीयूवी 300",
    "Mahindra Verito": "महिंद्रा वेरिटो",
    "Mahindra E Verito": "महिंद्रा ई वेरिटो",
    "Mahindra Xylo": "महिंद्रा ज़िलो",
    "Mahindra Bolero": "महिंद्रा बोलेरो",
    "Mahindra Alturas G4": "महिंद्रा अल्तुरास जी 4",
    "Mahindra Marazzo": "महिंद्रा मराज़ो",
    "Mahindra Bolero Power Plus": "महिंद्रा बोलेरो पावर प्लस",
    "Mahindra e2o Plus": "महिंद्रा ई 2o प्लस",
    "Mahindra XUV500": "महिंद्रा एक्सयूवी 500",
    "Mahindra TUV 300 Plus": "महिंद्रा टीयूवी 300 प्लस",
    "Mahindra KUV 100": "महिंद्रा केयूवी 100",
    "Mahindra Verito Vibe": "महिंद्रा वेरिटो वीबे",
    "Renault": "रेनॉल्ट",
    "Renault Lodgy": "रेनॉल्ट lodgy",
    "Renault KWID": "रीनॉल्ट क्विड",
    "Renault Captur": "रेनॉल्ट कैप्चर",
    "Renault Duster": "रेनॉल्ट डस्टर",
    "Tata Movus": "टाटा मूवस",
    "Tata Indica Vista": "टाटा इंडिका विस्टा",
    "Tata Estate": "टाटा एस्टेट",
    "Tata Venture": "टाटा वेंचर",
    "Tata Winger": "टाटा विंगर",
    "Tata Sierra": "टाटा सिएरा",
    "Tata Indica": "टाटा इंडिका",
    "Tata Indigo CS": "टाटा इंडिगो सीएस",
    "Tata Manza": "टाटा मांजा",
    "Tata H5X": "टाटा एच 5 एक्स",
    "Tata Sumo Victa": "टाटा सुमो विक्टा",
    "Tata Aria": "टाटा एरिया",
    "Tata New Safari": "टाटा न्यू सफारी",
    "Tata Indica V2": "टाटा इंडिका वी 2",
    "Tata Xenon XT": "टाटा जेनॉन एक्सटी",
    "Tata Spacio": "टाटा स्पासिओ",
    "Tata Indigo XL": "टाटा इंडिगो एक्सएल",
    "Tata Indigo": "टाटा इंडिगो",
    "BMW 3 Series": "बीएमडब्ल्यू 3 श्रृंखला",
    "BMW 4 Series": "बीएमडब्ल्यू 4 श्रृंखला",
    "BMW i3": "बीएमडब्ल्यू i3",
    "BMW X2": "बीएमडब्ल्यू एक्स 2",
    "BMW X4": "बीएमडब्ल्यू एक्स 4",
    "BMW X5": "बीएमडब्ल्यू एक्स 5",
    "BMW 8 Series": "बीएमडब्ल्यू 8 श्रृंखला",
    "BMW i8": "बीएमडब्ल्यू i8",
    "BMW X7": "बीएमडब्ल्यू एक्स 7",
    "Ford": "पायाब",
    "Ford Mustang": "फोर्ड मस्टंग",
    "Ford Freestyle": "फोर्ड फ्रीस्टाइल",
    "Ford Endeavour": "फोर्ड प्रयास",
    "Ford Ecosport": "फोर्ड Ecosport",
    "Ford Figo Aspire": "फ़ोर्ड फ़ीगो एस्पायर",
    "Ford Figo": "फोर्ड फिगो",
    "Renault Scala": "रेनॉल्ट स्कैला",
    "Renault Fluence": "रेनॉल्ट फ्लुएंस",
    "Renault Pulse": "रेनॉल्ट पल्स",
    "Renault Koleos": "रेनॉल्ट कोयोलोस",
    "Tata 45X": "टाटा 45 एक्स",
    "Tata H7X": "टाटा एच 7 एक्स",
    "Tata Tiago EV": "टाटा टियागो ईवी",
    "Tata EVision": "टाटा ईविजन",
    "Tata Harrier": "टाटा हैरियर",
    "Tata Tigor EV": "टाटा टॉगर ईवी",
    "Nissan": "निसान",
    "Nissan GTR": "निसान जीटीआर",
    "Nissan Terrano": "निसान टेरानो",
    "Nissan Micra Active": "निसान माइक्रो सक्रिय",
    "Nissan Micra": "निसान माइक्रोरा",
    "Nissan Sunny": "निसान सनी",
    "Mahindra e2o": "महिंद्रा ई 2o",
    "Mahindra Willys": "महिंद्रा विलीज़",
    "Mahindra Armada": "महिंद्रा आर्मडा",
    "Mahindra Inferno": "महिंद्रा इन्फर्नो",
    "Mahindra Jeep": "महिंद्रा जीप",
    "Mahindra Ingenio": "महिंद्रा इंजेनिओ",
    "Mahindra Voyeger 1997-2002": "महिंद्रा वॉयजर 1997-2002",
    "Mahindra Logan": "महिंद्रा लोगान",
    "Mahindra Rexton": "महिंद्रा रेक्सटन",
    "Mahindra U321 MPV": "महिंद्रा यू 321 एमपीवी",
    "Mahindra Quanto": "महिंद्रा क्वांटो",
    "Mahindra XUV700": "महिंद्रा एक्सयूवी 700",
    "Mahindra Marshal": "महिंद्रा मार्शल",
    "Aston Martin DBX": "एस्टन मार्टिन डीबीएक्स",
    "Datsun": "डैटसन",
    "Datsun GO Plus": "डैटसन गो प्लस",
    "Datsun GO": "Datsun जाओ",
    "Datsun RediGO": "Datsun RediGO",
    "Honda Civic 2006-2010": "होंडा सिविक 2006-2010",
    "Honda HR-V": "होंडा एचआर-वी",
    "Honda Mobilio": "होंडा Mobilio",
    "Honda City ZX": "होंडा सिटी जेएक्स",
    "Honda Civic 2010-2013": "होंडा सिविक 2010-2013",
    "Mahindra S 201": "महिंद्रा एस 201",
    "Mahindra XUV Aero": "महिंद्रा एक्सयूवी एयरो",
    "Mahindra eKUV100": "महिंद्रा ईकेयूवी 100",
    "Toyota": "टोयोटा",
    "Toyota Yaris": "टोयोटा यारीस",
    "Toyota Etios Cross": "टोयोटा ईटीओएस क्रॉस",
    "Toyota Etios": "टोयोटा इटिओस",
    "Toyota Innova Crysta": "टोयोटा इनोवा क्रिस्टा",
    "Toyota Corolla Altis": "टोयोटा कोरोला अल्टीस",
    "Toyota Fortuner": "टोयोटा फॉर्च्यूनर",
    "Toyota Land Cruiser": "टोयोटा लैंड क्रूजर",
    "Toyota Land Cruiser Prado": "टोयोटा लैंड क्रूजर प्राडो",
    "Toyota Etios Liva": "टोयोटा ईटीओस लिवा",
    "Toyota Prius": "टोयोटा प्रियस",
    "Volkswagen Jetta 2012-2014": "वोक्सवैगन जेटटा 2012-2014",
    "Volkswagen Jetta": "वोक्सवैगन जेटटा",
    "Volkswagen Phaeton": "वोक्सवैगन फाएटन",
    "Volkswagen 1600": "वोक्सवैगन 1600",
    "Volkswagen Caraville": "वोक्सवैगन कैरविल",
    "Volkswagen Beetle": "फॉक्सवैगन बीटल",
    "Volkswagen Polo GTI": "वोक्सवैगन पोलो जीटीआई",
    "Volkswagen Multivan": "वोक्सवैगन मल्टीवन",
    "Volkswagen CrossPolo": "वोक्सवैगन क्रॉसपोलो",
    "Volkswagen Touareg": "वोक्सवैगन टौअरेग",
    "Volkswagen": "वोक्सवैगन",
    "Volkswagen Tiguan": "वोक्सवैगन टिगुआन",
    "Datsun redi-GO" : "दत्सुण रेडी-गो",
    "Tata Tiago JTP":"टाटा टियागो जेटीपी",
    "Maruti WagonR 2018":"मारुति वैगनआर 2018",
    "Nissan Kicks":"निसान किक्स",
    "Volkswagen Vento": "वोक्सवैगन वेंटो",
    "Volkswagen Passat": "वोक्सवैगन पासैट",
    "Volkswagen Polo": "वोक्सवैगन पोलो",
    "Volkswagen Ameo": "वोक्सवैगन अमीओ",
    "Volkswagen GTI": "वोक्सवैगन जीटीआई",
    "Renault Scala": "रेनॉल्ट स्कैला",
    "Renault Fluence": "रेनॉल्ट फ्लुएंस",
    "Renault Pulse": "रेनॉल्ट पल्स",
    "Renault Koleos": "रेनॉल्ट कोयोलोस",
    "Tata 45X": "टाटा 45 एक्स",
    "Tata H7X": "टाटा एच 7 एक्स",
    "Tata Tiago EV": "टाटा टियागो ईवी",
    "Tata EVision": "टाटा ईविजन",
    "Tata Harrier": "टाटा हैरियर",
    "Tata Tigor EV": "टाटा टॉगर ईवी",
    "Largest Auto portal":"सबसे बड़ा ऑटो पोर्टल",
    "Car News India - All Latest Car Information And Auto News India":"कार समाचार भारत - सभी नवीनतम कार सूचना और ऑटो समाचार भारत",
    "Mercedes-Benz CLS":"मर्सिडीज-बेंज सीएलएस",
    "Skoda Karoq":"स्कोडा करोक",
    "Ford Endeavour 2019":"फोर्ड एंडेवर 2019",
    "Hyundai Elite i20":"हुंडई एलिट आई 20",
    "Audi Q8":"ऑडी क्यू 8",
    "Hatchback": "हैचबैक",
    "Sedan": "पालकी",
    "SUV": "एसयूवी",
    "MUV": "एमयूवी",
    "Luxury": "विलासिता",
    "Popular Brands": "लोकप्रिय ब्रांड",
    "View All Brands": "सभी ब्रांड देखें",
    "Hatchback Cars": "हैचबैक कारें",
    "Sedan Cars": "सेदान कारें",
    "SUV Cars": "एसयूवी कारें",
    "MUV Cars": "एमयूवी कारें",
    "Luxury Cars": "महंगी कार",
    "View All Hatchback Cars": "सभी हैचबैक कारें देखें",
    "View All Sedan Cars": "सभी सेडन कारें देखें",
    "View All SUV Cars": "सभी एसयूवी कारें देखें",
    "View All MUV Cars": "सभी एमयूवी कारें देखें",
    "View All Luxury Cars": "सभी लक्जरी कारें देखें",
    "Upcoming": "आगामी",
    "Latest": "नवीनतम",
    "Car Comparisons": "कार तुलना",
    "Add Car": "कार जोड़ें",
    "Used cars in": "में प्रयुक्त कारें",
    "Starting @": "शुरुआत में @",
    "Available": "उपलब्ध",
    "Cars": "कारें",
    "Used Cars available in your city": "प्रयुक्त कारें आपके शहर में उपलब्ध हैं",
    "Check the best deals": "सर्वोत्तम सौदों की जांच करें",
    "News to help choose your car": "आपकी कार चुनने में मदद करने के लिए समाचार",
    "Latest News": "ताज़ा खबर",
    "Expert Reviews": "विशेषज्ञ समीक्षा",
    "Featured Stories": "प्रमुख कहानियां",
    "Videos": "वीडियो",
    "Know more to choose better": "बेहतर चुनने के लिए और जानें",
    "More Cities": "अधिक शहर",
    "Select Budget": "बजट का चयन करें",
    "All Vehicle Types": "सभी वाहन प्रकार",
    "*Ex-showroom price": "* एक्स-शोरूम मूल्य",
    "The most searched cars": "सबसे खोजी गई कारें",
    "Maruti Dzire": "मारुति डिज़ायर",
    "Toyota Platinum Etios": "टोयोटा प्लैटिनम ईटीओएस",
    "View All Latest Cars": "सभी नवीनतम कारें देखें",
    "Alert me when": "जब मुझे चेतावनी दीजिए",
    "launched": "का शुभारंभ किया",
    "Nissan Terra": "निसान टेरा",
    "Bajaj Qute (RE60)": "बजाज कुट (आरई 60)",
    "Jeep Renegade": "जीप रेनेगेड",
    "sponsored": "प्रायोजित",
    "Download CarDekho's Free iOS App": "कारडेको की मुफ्त आईओएस ऐप डाउनलोड करें",
    "Change City": "शहर बदलें",
    "View All Upcoming Cars": "सभी आने वाली कारें देखें",
    "*Estimated price": "*अनुमानित दाम",
    "*Ex-showroom price in New Delhi": "* नई दिल्ली में एक्स-शोरूम कीमत",
    "Used cars in": "में प्रयुक्त कारें",
    "Trusted used cars by budget": "बजट द्वारा विश्वसनीय इस्तेमाल की जाने वाली कारें",
    "1-5 Lakh": "1-5 लाख",
    "5-10 Lakh": "5-10 लाख",
    "10-15 Lakh": "10-15 लाख",
    "New Cars in India": "भारत में नई कारें",
    "Featured cars": "फीचर्ड कारें",
    "1 Lakh - 5 Lakh": "1 लाख - 5 लाख",
    "5 Lakh - 10 Lakh": "5 लाख - 10 लाख",
    "10 Lakh - 15 Lakh": "10 लाख - 15 लाख",
    "15 Lakh - 20 Lakh": "15 लाख - 20 लाख",
    "20 Lakh - 50 Lakh": "20 लाख - 50 लाख",
    "Lakh - 1 Crore": "लाख - 1 करोड़",
    "50 Lakh - 1 Crore": "50 लाख - 1 करोड़",
    "Above 1 Crore": "1 करोड़ से ऊपर",
    "Jeep Wrangler Unlimited": "जीप रैंगलर असीमित",
    "Volvo XC90": "वोल्वो एक्ससी 9 0",
    "Isuzu ISUZU MUX": "Isuzu ISUZU MUX",
    "Tata Tigor JTP": "टाटा टॉगर जेटीपी",
    "Load More": "और लोड करें",
    "View All Cars": "सभी कारें देखें",
    "Best Cars": "सर्वश्रेष्ठ कारें",
    "Upcoming Cars in India": "भारत में आने वाली कारें",
    "Mahindra TUV300 2019": "महिंद्रा टीयूवी 300 201 9",
    "Toyota Camry 2019": "टोयोटा कैमरी 201 9",
    "Ford Figo 2018": "फोर्ड फिगो 2018",
    "Hyundai Elantra 2019": "हुंडई एलेंट्रा 201 9",
    "Jeep Cherokee": "जीप चेरोकी",
    "Nissan Leaf": "निसान पत्ता",
    "Porsche Macan 2019": "पोर्श मैकन 201 9",
    "Nissan Note e Power": "निसान नोट ई पावर",
    "Audi Q3 2019": "ऑडी क्यू 3 201 9",
    "Jeep Wrangler 2019": "जीप रैंगलर 201 9",
    "Volvo S60 2019": "वोल्वो एस 60 201 9",
    "Audi A6 2019": "ऑडी ए 6 201 9",
    "Audi TT 2019": "ऑडी टीटी 201 9",
    "Mercedes-Benz A-Class Sedan": "मर्सिडीज-बेंज ए-क्लास सेदान",
    "Hyundai Santa Fe 2019": "हुंडई सांता फे 201 9",
    "Car Offers & Discounts": "कार ऑफ़र और छूट",
    "Find offers on top brands": "शीर्ष ब्रांडों पर ऑफ़र खोजें",
    "View Complete Offer": "पूरा प्रस्ताव देखें",
    "CarDekho.com - Best place to buy New and Used Cars in India": "CarDekho.com - भारत में नई और प्रयुक्त कारें खरीदने के लिए सबसे अच्छी जगह",
    "Service Center": "सर्विस सेंटर",
    "Car Service Centers in India": "भारत में कार सेवा केंद्र",
    "New car service centers": "नई कार सेवा केंद्र",
    "Tools to help you": "आपकी मदद करने के लिए उपकरण",
    "Hyundai i20 2015-2017": "हुंडई आई 20 2015-2017",
    "Ford EcoSport": "फोर्ड इकोस्पोर्ट"
}
